### ISSUE TITLE
[System tests] Cert Manager seems to be useless for system tests

### ISSUE THREAD

**Issue by franvila** [kroxylicious/kroxylicious#1014]
**Describe the bug**
Since the beginning of system tests development, we have been deploying an instance of cert-manager, but it seems it has never used by any of the parties involved: Strimzi, Kroxylicious, Kafka. So it may be removed if there is no objections.

**Expected behavior**
Remove the cert-manager deployment.

**Comment by k-wall** [comment]
I anticipate that we will require such tests, but you are right we are not using it right now.  It will only ever be a subset of the tests that will need it, so spinning it up for every test case is pointless.
