### ISSUE TITLE
Verify if Kafka v3.7.0 works well in Kroxy 0.5.0

### ISSUE THREAD

**Issue by showuon** [kroxylicious/kroxylicious#1027]
If you have questions before creating this feature request, you can use the [GitHub Discussions](https://github.com/kroxylicious/kroxylicious/discussions) or use the [community Slack](https://kroxylicious.slack.com) chat.

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Kafka v3.7.0 is going to be released soon, we should test if Kroxy is compatible with it.

**Describe alternatives you've considered**
Not supporting Kafka v3.7.0, but that's not what we want.

**Additional context**

**Comment by k-wall** [comment]
We will be able to test against the 3.7 RC Maven artefacts https://lists.apache.org/list.html?dev@kafka.apache.org

**Comment by showuon** [comment]
Yes, that's what Strimzi usually did for RC build validation.
