### ISSUE TITLE
Add support for AES_GCM 256bit keys

### ISSUE THREAD

**Issue by SamBarker** [kroxylicious/kroxylicious#1044]
**Is your feature request related to a problem? Please describe.**
Our documentation says we support 256 bit keys but the implementation only offers 128 (as its the only version the JDK mandates)

**Describe the solution you'd like**
Make `AEC_GCM_256` available

**Describe alternatives you've considered**

**Additional context**

**Comment by k-wall** [comment]
For 0.5.0, we'll change the code to use 256 key length (no config options).  If platform doesn't support 256, the filter will fail.  For 0.6.0, we'll introduce config options.

**Comment by robobario** [comment]
We should make sure we test that the default/256bit specification does not work with a smaller key offered from the KMS. The Cipher transformation we use is compatible with multiple key lengths so I fear it may just quietly work if Vault returns a 128bit or 196bit key.

We should fail fast if Vault offers up a key with less than 32 bytes. We could also potentially truncate and use longer keys.
