### ISSUE TITLE
[System Tests] Create release branch in midstream repo on gitlab for system tests

### ISSUE THREAD

**Issue by franvila** [kroxylicious/kroxylicious#1112]
**Is your feature request related to a problem? Please describe.**
Due this error #1090, we have modified the code already tagged as 0.5.0, and we also need the tests to be repeatable, so we need to freeze the code somehow. 

**Describe the solution you'd like**
A new release branch **once the tests have been stabilized** must be created on gitlab [midstream](https://gitlab.cee.redhat.com/amq-streams/kroxylicious) project

**Comment by k-wall** [comment]
This isn't a concern for the community project.
