### ISSUE TITLE
Offer record transformation convenience as a public API

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#1127]
As part of implementing Record Encryption we have introduced some abstractions for manipulating Records in Produce Requests and Fetch Responses while preserving batching and batch metadata.

[RecordStream](https://github.com/kroxylicious/kroxylicious/blob/a1bb61c5ec273c1154e554cef667b20318afd044/kroxylicious-filters/kroxylicious-record-encryption/src/main/java/io/kroxylicious/filter/encryption/records/RecordStream.java)
[RecordTransform](https://github.com/kroxylicious/kroxylicious/blob/main/kroxylicious-filters/kroxylicious-record-encryption/src/main/java/io/kroxylicious/filter/encryption/records/RecordTransform.java)
[BatchAwareMemoryRecordsBuilder](https://github.com/kroxylicious/kroxylicious/blob/a1bb61c5ec273c1154e554cef667b20318afd044/kroxylicious-filters/kroxylicious-record-encryption/src/main/java/io/kroxylicious/filter/encryption/records/BatchAwareMemoryRecordsBuilder.java)

A single MemoryRecords of topic-partition data can be comprised of multiple batches. Each batch has some metadata. There are some special cases to consider like batches that have had 100% of their records removed and control batches that carry control messages like transaction commit/rollbacks. For the proxy to act transparently we want to ensure messages remain batched the same way and these special batches are preserved.

Making this functionality available to users as part of a public API should enable them to implement message transforms safely without having to rediscover how to work with batches (which is a bit ugly as we discovered, requiring the BatchAwareMemoryRecordsBuilder to build multi-batch MemoryRecords)

**Comment by gracegrimwood** [comment]
Triaged 10/04/2024: we should check if these classes are ready for the public API. We could also put it in a seperate module from everything else.
