### ISSUE TITLE
Custom tenant topic name prefix

### ISSUE THREAD

**Issue by michaelandrepearce** [kroxylicious/kroxylicious#1162]
**Is your feature request related to a problem? Please describe.**
Current the topic prefix applied seems to be hardcoded, in the underlying kafka cluster as <virt-cluster-name>-

e.g. if topic is foo.bar, and cluster name is john - underlying topic becomes john-foo.bar , because normally seperators are "." or "_" for kafka the "-" can be problematic.

**Describe the solution you'd like**
It would be great if in configuration we could simply define the topic prefix per virtual cluster as a string e.g. "sid_" or "george." so that then this string was applied , this way giving end user control on the prefix and any special character or seperators being used.

**Describe alternatives you've considered**
Living with the "-" and try fix all the other bits to work with "-" seperator :( 

**Additional context**
It looks like this maybe relatively easy to change, by making this non-static, or adding into the filter context another property a field to be set, if set use, else keep existing logic.

**Comment by SamBarker** [comment]
Hey @michaelandrepearce thanks for raising this. 

The prefix is currently based on the name of the _virtual_ cluster, I generally think of _underlying_ as being the actual cluster of brokers, which seems like a sensible default.  

Do you have a need for specific prefixes? Would changing the separator solve your problem? I don't think we have any strong feelings about what the prefix or separator should be but we do want to keep things as simple out of the box as possible. So I'm a little wary of adding a config definition just to change the separator character.

**Comment by michaelandrepearce** [comment]
The issue I see of just changing the hard coded seperator is whilst I would want/need underscore separator others may need alternative, e.g. in their systems they maybe using one of the other separator symbols allowed those if I'm not being mistaken being either dot "." , underscore "_" or dash "-"

**Comment by k-wall** [comment]
https://github.com/kroxylicious/kroxylicious/pull/1168 @michaelandrepearce does this PR address your use-case?  all comments welcomed.

**Comment by michaelandrepearce** [comment]
@k-wall looks good I think, i didn't see an update in examples or docs, to be 100% as isn't quite clear what to set without example or doc.

**Comment by k-wall** [comment]
Thanks for the confirmation.

We are missing documentation for the multi-tenant filter right now.   In the meanwhile you should be able to configure it like so:

```yaml
 filters:
    - type: MultiTenantTransformationFilterFactory
      config:
        prefixResourceNameSeparator: "."
```

The config block is optional.  If you don't supply it, the system will default to `-`.
