### ISSUE TITLE
[System Tests] Fix strimzi installation to select the proper version and not installing the latest one

### ISSUE THREAD

**Issue by franvila** [kroxylicious/kroxylicious#1209]
**Describe the bug**
After the changes included in Strimzi 0.41.0 not supporting `KafkaNodePools` feature gate, our tests cases are broken because we always install the latest version.

**Expected behavior**
We should install the currently supported version taken from the main `pom.xml` file and modify the installation from the url to use helm charts/github releases selecting the proper version.

**Comment by k-wall** [comment]
Yes, that sounds sensible.  We should never be taking the 'latest' of any dependency.  We should always tie to a version in order to get repeatability over time.
