### ISSUE TITLE
RecordEncryptionST should execute tests against AWS (LocalStack) too

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#1219]
**Is your feature request related to a problem? Please describe.**

Once the AWS KMS integration is landed, we should adapt the `RecordEncryptionST` to test against AWS LocalStack.

It appears that there is a [Helm Chart for Localstack](https://github.com/localstack/helm-charts) so _hopefully_ the pattern established for Vault should apply nicely.  

`RecordEncryptionST` current hard-wires the Vault KMS provider.  That hard wiring need to be broken.  It should probably use `@TemplateTest`s like `RecordEncyrptionIT` and `KmsIT` and let the KMS be plugged into the test.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by franvila** [comment]
Note: try to reach an already implemented solution for AWS cloud instead of LocalStack

**Comment by k-wall** [comment]
We _might_ want a system test that can run against either localstack or real AWS.
