### ISSUE TITLE
Investigate and maybe switch to Netty 5

### ISSUE THREAD

**Issue by tombentley** [kroxylicious/kroxylicious#124]
We're currently using Netty 4. Netty 4 is effectively EoL and Netty development is now focused on version 5. As an early stage project there is no particular benefit (e.g. in terms of compatibility/risk) in sticking with version 4. Switching to version 5 would bring these benefits to the project

1. Allow us to benefit from improvements in Netty 5 which won't be back-ported to 4.
2. Allow us to switch to JDK 17 for all the code without taking a performance hit

We should start investigating this, and make the switch if no major problems are found.

See also #71.

**Comment by robobario** [comment]
triaged, netty 5 still in the works and doesn't look to be coming soon

**Comment by k-wall** [comment]
The last alpha for Netty 5 was https://netty.io/news/2022/09/28/5-0-0-Alpha5.html

**Comment by tombentley** [comment]
Looks like Netty 5 is no longer the direction being pursued by the Netty community, who are now focussing on 4.2. Closing this.
