### ISSUE TITLE
Warning logged when running KafkaClusterIT

### ISSUE THREAD

**Issue by tombentley** [kroxylicious/kroxylicious#125]
When running io.kroxylicious.proxy.KafkaClusterIT the following warning gets logged: 

> 2023-02-03 14:52:06 WARN  org.apache.kafka.common.network.ChannelBuilders:158 - Broker configuration 'ssl.client.auth' is applied only to SSL listeners. Listener-prefixed configuration can be used to enable SSL client authentication for SASL_SSL listeners. In future releases, broker-wide option without listener prefix may be applied to SASL_SSL listeners as well. All configuration options intended for specific listeners should be listener-prefixed.

We should investigate and fix this. If nothing else it might obscure other more important logging.

**Comment by k-wall** [comment]
@franvila did your change fix this already?

**Comment by franvila** [comment]
I didn't see this error before. When is it happening?

**Comment by k-wall** [comment]
No point fixing this in KafkaClusterIT, as this will disappear from this project once the code starts to depend on the  junit-ext.
However, the issue exists there too.   We should fix that. 

https://github.com/kroxylicious/kroxylicious-junit5-extension/issues/31



This will stop 

o.kroxylicious.testing.kafka.KafkaClusterTest#kafkaClusterZookeeperModeSASL_SSL_ClientUsesSSLClientAuth
