### ISSUE TITLE
Logging "higher" level Apache Kafka messages

### ISSUE THREAD

**Issue by tombentley** [kroxylicious/kroxylicious#1281]
### Discussed in https://github.com/kroxylicious/kroxylicious/discussions/568

<div type='discussions-op-text'>

<sup>Originally posted by **ppatierno** August 17, 2023</sup>
I searched through the repo and in any guide but I couldn't find any good description about the two logging flags `logFrames` and `logNetwork`.
As far as I understood they are anyway strictly related to Netty stuff, so about printing the actual content moving across the network.
What I was looking for was something for logging the "higher" level Apache Kafka messages exchanged between proxy and client (and even maybe between proxy and broker). Is it anything like that available? Is there a plan to add?
Anyway I would document more the two above `logXXXX` flags.</div>

**Comment by k-wall** [comment]
logFrames and logNetwork are already documented in the DEV_GUIDE.md.
There is a filter that logs Kafka RPCs flowing through the proxy here.
