### ISSUE TITLE
[System tests] Provide more info when the restartKafkaBroker test case fails

### ISSUE THREAD

**Issue by franvila** [kroxylicious/kroxylicious#1283]
**Is your feature request related to a problem? Please describe.**
We would need more info when a Kafka Broker is not restarted for some reason during the [test run.](https://master-jenkins-csb-amq-streams.apps.ocp-c1.prod.psi.redhat.com/job/amq-streams-components/job/release-pipeline/26/console)

**Describe the solution you'd like**
If that error happens, we should collect the logs of the pod to know the reason of the failure and take some initiative depending on the failure (finish the test, wait more time, restart again...)

**Comment by k-wall** [comment]
In other life, we just used to get the kubernetes state whenever a test failed.  [afterAll](https://github.com/EnMasseProject/enmasse/blob/d0724e2d2aaeda427937be1ffeba707017dd8f0e/systemtests/src/main/java/io/enmasse/systemtest/listener/JunitCallbackListener.java#L88)
