### ISSUE TITLE
Provide a thread pool for blocking work

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#1323]
**Is your feature request related to a problem? Please describe.**

As a Filter Author I may want to integrate with a library that makes blocking calls.

Blocking behaviour inside Filter methods is harmful to the proxy's netty implementation. Numerous Channels/Filters share a single event loop thread. If I block up the eventloop in a Filter invocation, then other unrelated clients that happen to have their connections being handled by the same eventloop will be delayed.

Currently the user would have to handle offloading blocking work to another Thread themselves, perhaps managing it at a FilterFactory level. Each Filter then has to write their own code to manage the thread/pool lifecycle. This is repetitive and puts the thread management outside of what the Framework can monitor.

The apicurio validation filter is one example where we want to use the battle-tested apicurio library, but it only has a sync api. We can hand the blocking work off to a blocking pool.

**Describe the solution you'd like**
The proxy could offer a blocking thread pool, analogous to a vert.x worker pool. It would be optionally configurable in the proxy config like:

```
blockingPool:
  corePoolSize: 1
  maxPoolSize: 100
```

Maybe the BlockingPool implementation should be provided via the Plugin mechanism so we have a place to plug in different implementations in case we want fixed/cached etc.

and it would be exposed via the FilterFactoryContext like:

```
// provides an extension point in future
interface BlockingPool extends ScheduledExecutorService {
}
```

```
interface BlockingPool {
    BlockingPool blockingPool()
}
```

The BlockingPool might also be a place to add convenience methods that could enable Filters to submit work to the blocking pool, but then ensure than completion is driven by the filterDispatchThread.

**Comment by robobario** [comment]
I've also seen other frameworks with named pools, so you can have arbitrary pools listed like:

```
pools:
  - name: my-pool-name:
    coreSize: x
    maxSize: y
```

and access them by name. But maybe the single blocking pool is enough to get going.

**Comment by SamBarker** [comment]
We see merit in the idea, but don't currently have confidence that this is the right way to grow our API surface.

**Comment by tombentley** [comment]
The merit of providing this as part of the runtime is consistency between filters, and the ability to provide centralized monitoring (e.g. metrics) about thread usage for operators. 

But part of the concern about API surface is we're slowing building out an API that's like an ad hoc version of what Vert.X gives you.  This issue is about a thread pool, but it's easy to imagine the case being made for a common HTTP client for all the filters that need to talk REST externally.
