### ISSUE TITLE
In the PR, link the previous flamegraphs so that we can diff before and after

### ISSUE THREAD

**Issue by lucamolteni** [kroxylicious/kroxylicious#1335]
If you have questions before creating this feature request, you can use the [GitHub Discussions](https://github.com/kroxylicious/kroxylicious/discussions) or use the [community Slack](https://kroxylicious.slack.com) chat.

**Is your feature request related to a problem? Please describe.**

After https://github.com/kroxylicious/kroxylicious/pull/1181 one can see the new flame graph, but cannot easily compare it to the previous one

**Describe the solution you'd like**

A way to see the flame graph of the execution before the PR

**Describe alternatives you've considered**

I think perf jobs are already ran each time there's a merge and on main, so we don't need to regenerate them, but rather to link to the current main files

**Additional context**.

**Comment by franvila** [comment]
MR done in the corresponding strimzi-ci repository. Waiting for approval.

The files created in the artifacts would be added to the `async_profiler_previous` directory. 

![Screenshot from 2024-07-11 12-13-23](https://github.com/kroxylicious/kroxylicious/assets/57452611/9ab77930-6d16-4fb7-b01b-a787ba3039f6)

At the LastSuccessfulBuild Artifacts they will appear all together, but they have different timestamps, so we can distinguish between the old and the current ones:

![Screenshot from 2024-07-11 12-13-08](https://github.com/kroxylicious/kroxylicious/assets/57452611/015c2fb1-b0e7-45a5-9dbb-9ab98e54cac2)

**Comment by lucamolteni** [comment]
Thank you @franvila ! I can't wait to use this

**Comment by franvila** [comment]
Merged. You can use it once Jenkins is reloaded
