### ISSUE TITLE
AwsKmsTestKekManager should use the real rotate endpoint when running against real AWS

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#1338]
**Is your feature request related to a problem? Please describe.**

AWS LocalStack doesn't implement key rotation.  The AWS KMS tests work around the this by creating a new key instead,  repointing the alias, leaving the existing key in place.  This is a reasonable approximation for rotation but is not perfect.

#1336 is adding the ability to run the tests against real AWS.  When run against real AWS, it must use the real endpoint so that we have the ability to properly test the rotate use-case as it will be used in production.

**Describe the solution you'd like**

Change AwsKmsTestKmsFacade.AwsKmsTestKekManager#rotate to that it tries the real rotate endpoint first.  Fallback to the create/delete strategy if the endpoint doesn't exist.  This approach will mean if/when AWS implement https://github.com/localstack/localstack/issues/10723, the test suite will remain compatible.

**Describe alternatives you've considered**

**Additional context**

**Comment by k-wall** [comment]
The ST doesn't actually test key rotation key, so even though io.kroxylicious.systemtests.resources.kms.aws.KubeAwsKmsCloudTestKmsFacade.AwsKmsCloudTestKekManager#rotate calls the rotate API, we are not currently calling it.

We should add a rotateKeyTest to the RecordEncryptionST, however, we need a solution to #1339 first.

**Comment by franvila** [comment]
I created #1341 to do that few days ago
