### ISSUE TITLE
kroxylicious-admin user permissions for Record Encryption filter

### ISSUE THREAD

**Issue by franvila** [kroxylicious/kroxylicious#1348]
**Suggestion / Problem**
Following the official [documentation](https://kroxylicious.io/docs/v0.6.0/#administrator-actor-2) of Kroxylicious, when implementing system tests, I found that we cannot delete the KEK created to keep everything clean, so I need to add some more permissions to do that: [deleting-keys-adding-permission](https://docs.aws.amazon.com/kms/latest/developerguide/deleting-keys-adding-permission.html)

**Documentation Link**
Here is where the aforementioned documentation lives, but maybe it should not be added here as this is only a test issue.
[Link](https://github.com/kroxylicious/kroxylicious.github.io/blob/main/docs/v0.6.0/_files/available-filters/record-encryption/aws-kms/setup.adoc#administrator-actor)
But I'd suggest to add this documentation somewhere to avoid redo things in the future when testing AWS KMS.

**Comment by k-wall** [comment]
The documentation is trying to convey that the fact that something outside the system needs to be responsible for creating KEKs that will be used by Record Encryption. It provides guidance as to what permissions that user needs.  The intent was to help a user understand what's required so they can map those requirements into their organisation structure.   

Currently the deletion of KEKs is not something that is considered by the documentation.  Indeed, there is no documentation proceeds that allows the user to know with certainty that a KEK is no longer required.

**Comment by robobario** [comment]
I think this can be safely disconnected from 0.7.0, is there still a task in here @franvila?

> I'd suggest to add this documentation somewhere to avoid redo things in the future when testing AWS KMS.

Do you have a place in mind for documenting some testing knowledge like this?

**Comment by franvila** [comment]
@k-wall told in the last sync meeting that he will take this issue soon to try to include it in 0.7.0.
