### ISSUE TITLE
Why doesn't DEV_GUIDE and Github actions make use of our Maven wrapper?

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#1412]
We've gone to the bother of including a Maven wrapper in the project, but we don't actually seem to advocate for its use.

In the `DEV_GUIDE.md`:

* Apache Maven is called out as an external dependency that the developer needs to provide.
* The [minimum version](https://github.com/kroxylicious/kroxylicious/blob/main/DEV_GUIDE.md#build-prerequisites) is different to that used by the [wrapper](https://github.com/kroxylicious/kroxylicious/blob/main/.mvn/wrapper/maven-wrapper.properties).
* The example commands don't illustrate the use of `mvnw`.

The Github Actions don't used `mvnw` but the version from the toolchain.

We should either use `mvnw` consistently, or remove it.

As we care about maven version, we should probably also make use of https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html

**Comment by robobario** [comment]
remove the maven wrapper. split an issue for adding maven version enforcer
