### ISSUE TITLE
Record Validation Filter name inconsistency

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#1414]
We've got some inconsistencies on the name we use for the Record Validation Filter.   

Public API:

* the filter factory is called `ProduceValidationFilterFactory` (this name appears in the user's config)
* the documentation introduces the filter as "Schema Validation"

The following names are used but aren't part of the public API.

* the maven module is called `kroxylicious-record-validation` 
* the java package name for the filter implementation`io.kroxylicious.proxy.filter.schema` 
* the docs use the directory name `schema-validation` and this naming appears in the fragment filenames (`con-schema-validation`).

The filter has both Json Syntax and Schema Validation capabilities so "Schema Validation" (docs) is too narrow.   ProduceValidation is sufficiently broad, but it is not really in keeping with the precedent set by "Record Encryption" (which doesn't mention Producer).

I'm in favour of "Record Validation".

**Comment by robobario** [comment]
minimum is to ensure user facing names in config are consistent

**Comment by robobario** [comment]
+1 to  "Record Validation"

**Comment by SamBarker** [comment]
Yes! I suggested going ahead with the rename on a PR and ticked off confirming it on my mental todo list.
