### ISSUE TITLE
Jenkins test piplines broke with Apache Kafka 3.8.0

### ISSUE THREAD

**Issue by SamBarker** [kroxylicious/kroxylicious#1506]
See #1505 for the workaround. This issues is for the follow up question:

> 1. How could we have found this earlier - Should we require a system test pass before merging?

_Originally posted by @SamBarker in https://github.com/kroxylicious/kroxylicious/pull/1505#pullrequestreview-2293884146_

**Comment by k-wall** [comment]
> Add system tests to the PR checklist.

PR raised #1508
