### ISSUE TITLE
Some WARN-level logs are not printed when DEBUG logging is enabled

### ISSUE THREAD

**Issue by gracegrimwood** [kroxylicious/kroxylicious#1634]
**Describe the bug**

> When log level is set to `DEBUG` or `ALL`, the `WARN`-level logs in `RecordEncryptionFilter.java` don't print. This seems to be because a value (a `Throwable`) is only passed to `setCause` when `DEBUG` logging is enabled, and whatever that value is seems to silently break something in the logger _somewhere_ and so no log is printed.
> 
> I found this while looking at the `RequestNotSatisfiable` issue on OpenShift, where the warning I was looking for appeared in the logs when logging level was set to default values, but disappeared from the logs (even though the same behaviour was occurring) when I turned the logging levels up to `DEBUG` or `ALL` via the `KROXYLICIOUS_ROOT_LOG_LEVEL` environment variable.

_Originally posted by @gracegrimwood in https://github.com/kroxylicious/kroxylicious/pull/1616#issue-2677913543_

**To Reproduce**

> 1. Turn the logging level up to DEBUG or higher using the `KROXYLICIOUS_ROOT_LOG_LEVEL` environment variable
> 2. Trigger any condition in the filter that would trigger that code to run.
>     - I was trying to reproduce the behaviour seen in #1526, with the setup described in [this comment](https://github.com/kroxylicious/kroxylicious/issues/1526#issuecomment-2486958774), but I'm sure there are other, simpler things you could do that would trigger this code
>     - I think that behaviour in the above issue could be reproduced at a smaller scale by setting max encryptions per DEK to 1 and then pointing a minimum of 2 producers at the proxy instance, all sending produce requests continuously (the bug relies on multiple produce requests being in flight at the time a DEK expires, so more producers = more requests = more likely to occur)
> 
> Then do the same with logging level set to default values. At default levels, this code runs and a message is printed as we expect. At DEBUG there is no log printed, and no message to indicate why a log was not printed (or that an attempt at printing a log failed).

_Originally posted by @gracegrimwood in https://github.com/kroxylicious/kroxylicious/issues/1616#issuecomment-2492363958_

**Expected behavior**
When `DEBUG` logging is enabled, `WARN`-level logs should still print when they normally would if `DEBUG` logging was disabled. In the case of the `RequestNotSatisfiable` logs and similar, they should also print a stack trace in addition to their usual message when `DEBUG` logging is enabled.

**YAML files and logs**

I won't attach any files here as they are quite large (>1gb).

**Additional context**

> I've tested on minikube and I don't see this issue, which is very weird. I'll try on OpenShift Local and then try on another ROSA cluster, I have a theory that it might actually be something to do with how OpenShift handles container logs...

_Originally posted by @gracegrimwood in https://github.com/kroxylicious/kroxylicious/issues/1616#issuecomment-2499436776_

> So after some testing on a ROSA cluster, I think this is potentially an issue of log volume.
> 
> I observed that under heavy load with `DEBUG` logging enabled the messages go missing, but when the load is reduced the messages appear. To reduce load on the proxy, I reduced the value of `maxEncryptionsPerDek` in the proxy config from 5000 to 500<sup>[*1](#20241127-note-1)</sup> and reduced the number of producers<sup>[*2](#20241127-note-2)</sup> concurrently making requests from 5 to 2.
> 
> I found that when the value of `maxEncryptionsPerDek` was reduced (I tried the values 500 and 2) but the number of producers was not then the messages do not appear, so it's not tied to that specifically. Reducing the number of producers without reducing `maxEncryptionsPerDek` does not reliably produce the behaviour which triggers these messages, so I haven't bothered to test it.
> 
> I'm going to see if I can reproduce this behaviour with any other `WARN`-level logging in Kroxylicious, and try to work out if it's a problem with just this filter, this specific log message, or something else. I'm also going to close this PR and raise an issue for this, because my change here won't actually fix this problem.
> 
> ---
> 
> <sub><a name="20241127-note-1">*1</a> I also tried values 2000, 1000, and 2, and I found that for both 1000 and 2000 the messages did not appear, while for 2 the messages appeared quite frequently but the constant connection errors in the producer logs made it hard to see what was going on.</sub>
> 
> <sub><a name="20241127-note-2">*2</a> The producers in question are simply a deployment of [this image](quay.io/ggrimwoo/kroxy-perf-test:0.0.1-test-amd64), which is built using the following Dockerfile:</sub>
> ```
> FROM docker.io/apache/kafka:3.8.1
> ENTRYPOINT /opt/kafka/bin/kafka-producer-perf-test.sh --topic ggrimwookroxylicioustest --num-records 90000 --throughput 500 --producer-props bootstrap.servers=kroxylicious-service.kroxylicious.svc.cluster.local:30192 --record-size 1000 --print-metrics
> ```

_Originally posted by @gracegrimwood in https://github.com/kroxylicious/kroxylicious/issues/1616#issuecomment-2502602237_

**Comment by k-wall** [comment]
@gracegrimwood is this issue closeable?  If I understand your comments on #1616 this issue is invalid.

**Comment by SamBarker** [comment]
I think from a conversation with @gracegrimwood that we should be recommending against the console appender in log4j based on performance numbers and documenting how to write to log file and expose that to kubernetes.

We should also switch our images to use log4j2 async loggers.

So I vote to leave this issue open until we've addressed those points.

**Comment by k-wall** [comment]
Sorry, I'm not grasping the root cause.   Are we really saying Log4j is dropping messages under load?  I've never heard of anything like this before.

**Comment by SamBarker** [comment]
No, not log4j!

Kube fails to keep up and drops logs is my understanding. 

However the performance numbers for the console appender are significantly worse than file. So if we log to a file we have reliable logging and better performance.

**Comment by SamBarker** [comment]
No, not log4j!

Kube fails to keep up and drops logs is my understanding. 

However the performance numbers for the console appender are significantly worse than file. So if we log to a file we have reliable logging and better performance.
