### ISSUE TITLE
Upstream TLS timeout too short

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#1659]
In [#1650](https://github.com/kroxylicious/kroxylicious/issues/1650#issuecomment-2532906889_), the user noticed that the TLS upstream timeout is rather aggressive (100ms).   The Netty's default is 10,000ms.   

>For your information, I have adapted the [SSL handshake timeout](https://github.com/kroxylicious/kroxylicious/blob/d09869e60edb3349e33cfb44389327641ee24560/kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java#L484) because 100ms was not enough. 
> Maybe a dedicated conf will be a good fit. 

> _Originally posted by @LGouellec in https://github.com/kroxylicious/kroxylicious/issues/1650#issuecomment-2532906889_
   

We should:

* reconsider if our default is good and/or
* consider if adding configuration to allow the timeout to be tuned is a good idea.

**Comment by k-wall** [comment]
AFACS 0.8.1 didn't adjust the timeout at all, so I think this could be considered a regression on main.

**Comment by SamBarker** [comment]
Ah rats some debugging change from playing with TLS while doing the state machine work got leaked in. Let's just revert the timeout and stick to the netty defaults
