### ISSUE TITLE
Rename admin to metrics in the config model

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#1669]
In the configuration we currently have:

```
adminHttp:
  endpoints:
    prometheus: {}
```

in reality it is not an admin interface at all.  It is just a just a interface for metrics.

I don't think we have any intent to introduce an Admin API any time soon (indeed, that would run contrary to the declarative direction we are going with the Operator).

I am suggesting we rework the configuration model so that it is in terms of metrics alone.

**Comment by tombentley** [comment]
Closing this. We can always reopen if we decide to implement reloading in a different way.
