### ISSUE TITLE
aciidoc github pages action clashes with continuous performance tests action, historical benchmarks are deleted

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#177]
**Describe the bug**
Performance benchmark results are wiped from the `gh-pages` branch by the asciidoc action when commits are pushed to main. The  `asciidoctor-ghpages-action` action rebases the branch down to a single commit and blows away other changes.

**To Reproduce**
1. fork the repo
2. Create a PR against your fork's main and run `/perf` and let the action run until it commits to `gh-pages` on your fork
3. Commit and push something to main (on your fork! :grin:, or reconfigure the actions to run against a branch instead of main)
4. the asciidoctor action runs and pushes to `gh-pages` in your fork, rebasing away the performance results.

**Expected behavior**
The performance test results should not be removed and should co-exist with the asciidoctor generated HTML when we push to `main`.

**Additional context**
The benchmark action wants to use the `gh-pages` branch for storing results for comparison and detecting regressions.

The current asciidoctor action looks like it only supports this rebase flow, so maybe we could change to use one action to [build the asciidocs](https://github.com/marketplace/actions/build-asciidoctor-action) and a second to [deploy to the github pages branch](https://github.com/marketplace/actions/deploy-to-github-pages), this deploy action allows you to keep the pages history rather than rebasing to a single commit.

Alternatively the benchmark action supports pushing to a separate repository, so we could have a benchmark-results repo wired up to kroxylicious.io

**Comment by robobario** [comment]
ping @franvila

**Comment by franvila** [comment]
Thanks for that catch @robobario ! If needed we can create another branch for the benchmark, it is really easy to be configured there, but we have to manage how to make it visible in let's say `kroxylicious.io/bechmark`. WDYT?

**Comment by robobario** [comment]
I don't know if there's a way to present two branches of the same repo in github pages. It looks like you [can't](https://github.com/orgs/community/discussions/21582). Also yeah there's a seperate issue in there to get it exposed, `.benchmark` isn't exposed by default, looks like you can add a file to allow the `.` prefixed folders to be [presented by Jekyll](https://github.com/orgs/community/discussions/22227#discussioncomment-3235986), or change the dir to not have a dot prefix.

So yeah, I'm not sure what's nicest, it would be cool for the results to be in the same repository. I can look into changing how the asciidocs are generated and see if the two sources of documents can co-exist.

**Comment by robobario** [comment]
There is also the option of making a `kroxylicious/benchmarks` repository and configuring the benchmark action to push to there. We could then expose that repositories github pages as `kroxylicious.io/benchmarks/*`

**Comment by franvila** [comment]
> I don't know if there's a way to present two branches of the same repo in github pages. It looks like you [can't](https://github.com/orgs/community/discussions/21582). Also yeah there's a seperate issue in there to get it exposed, `.benchmark` isn't exposed by default, looks like you can add a file to allow the `.` prefixed folders to be [presented by Jekyll](https://github.com/orgs/community/discussions/22227#discussioncomment-3235986), or change the dir to not have a dot prefix.

Yeah we forced to be `.benchmark` to avoid publishing directly and make it public.
