### ISSUE TITLE
Performance Test results recorded against the wrong commit

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#181]
**Describe the bug**
I triggered a performance test action against a dependabot branch. The [action completed successfully](https://github.com/kroxylicious/kroxylicious/actions/runs/4370692241), and checked out the correct branch. However in [the commit](https://github.com/kroxylicious/kroxylicious/commit/a5832b37cfb914bfb0434862e14b7eb2c96f26d8) pushed to the performance-results branch all the details are about the head commit on `main`.

**To Reproduce**
1. Trigger a performance test using a comment on a PR (the PR must be from a branch in kroxylicious/kroxylicious) with a head commit different from the head commit on main
2. View the results pushed to the `performance-results`
3. The latest results should reference the head commit on `main` rather than the head commit on the PR branch.

**Expected behavior**
Performance test results record the commit id, message, author, timestamp for the commit that was performance tested

**Additional Context**
I _think_ the problem is that the benchmark action is run in a context that knows the workflow is running from `main` and so that's what it uses when detecting the commit to inject into the results.

I've created an [issue](https://github.com/benchmark-action/github-action-benchmark/issues/157) in the benchmark-actions repo to see if they like the idea of integrating with `issue_comment` events directly or adding parameters so we could pass a ref, owner and repository to the action so it could use that to load the data.

**Comment by robobario** [comment]
FYI @franvila

**Comment by franvila** [comment]
Thank you @robobario! Yeah it seems like an issue in the `benchmark-actions`. I didn't realize about that

**Comment by franvila** [comment]
@robobario is this issue already solved? I know you made a change regarding the PR number, but I don't know if there is something else remaining for this bug

**Comment by robobario** [comment]
This issue is not solved yet, the other fix was to enable the tests to run against a PR from a fork #182 

For a PR comment performance run, In the performance-results branch it will be recorded that the result is for the head commit of `main`, but we ran the tests for some other commit.

**Comment by robobario** [comment]
I looked a little into how to fork/modify the action so we could contribute that change but hadn't made much progress in figuring out how to build/test the changes. Here's [my changes](https://github.com/benchmark-action/github-action-benchmark/commit/b206bda3160f5577aa5015bfdb2148fa5e76e7b7)

**Comment by robobario** [comment]
@franvila what do you think about moving my fork into a public `kroxylicious` fork and using that for now instead of the upstream action?

**Comment by robobario** [comment]
It's not too bad, there's a script in their repo that builds a distribution and commits it to some named branch. You push it up and tag it then can refer to it like `organization/repo@tag` from workflows. I was able to test the changes in my fork this way.

But yeah, maintaining a fork isn't appealing.
