### ISSUE TITLE
Clean up the javadoc warnings

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#198]
There are screeds of javadoc warnings when running the maven build. 

* This has a negative impact on productivity. 
* Developers are less likely to notice impactful warnings amongst the noise. 
* Our javadoc will tend to rot, as there'll be an assumption that we don't care about it.  

We should clean up the warnings.

Run `mvn verify` and look for the screeds of yellow.

_Originally posted by @k-wall in https://github.com/kroxylicious/kroxylicious/issues/195#issuecomment-1467944993_

**Comment by k-wall** [comment]
@racheljpg wondering if you could put this on your todo list as a low priority/background item.  Don't let it block the more important tasks.

**Comment by tyagi-data-wizard** [comment]
Hello @k-wall , 
I am new to open source, can I work upon this?

**Comment by k-wall** [comment]
Welcome, yes, go ahead.

**Comment by tyagi-data-wizard** [comment]
Getting some error while pulling the code to my local, any idea on this?
" no marketplace entries found to handle kroxylicious-krpc-plugin:0.1.0-SNAPSHOT:generate-multi in Eclipse.  "

**Comment by k-wall** [comment]
#259 chipping away
