### ISSUE TITLE
Avoid copy to ByteBuffer if possible

### ISSUE THREAD

**Issue by gunnarmorling** [kroxylicious/kroxylicious#2]
See `ByteBufAccessor.java::readByteBuffer()`; as per @franz1981, we may be able to avoid that copy using `ByteBuf::internalNioBuffer()`.

**Comment by gunnarmorling** [comment]
We also probably should abandon using Kafka-provided classes such as `MemoryRecords`, as they are immutable and challenging to work with for our use case. Having a lighter-weight access to the underlying buffers will proabably work more to our advantage.

**Comment by robobario** [comment]
triaged - closing as stale - we have plans to explore performance so this may crop up again after some analysis
