### ISSUE TITLE
Run integration tests with Netty leak detector

### ISSUE THREAD

**Issue by SamBarker** [kroxylicious/kroxylicious#202]
Given one of the core tasks of the proxy is to read and transform Kafka messages we are manipulating Netty ByteBuffers (either directly via the MemoryRecordsHelper or indirectly through the Kafka Message Encoder). Kroxylicious is a infrastructure service and thus expects to be available for prolonged periods of time without being restarted. Thus we want to ensure we are managing memory correctly and efficiently.

**Describe the solution you'd like**
We should ensure that all our integration tests run with the Netty [Leak Detector](https://netty.io/wiki/reference-counted-objects.html#leak-detection-levels) set to `PARANOID`. 

We should then fail the build if `LEAK:` appears in the test output (this will require us to ensure we enable logging during build runs).

It will be up to the people building distributions or deploying kroxylicious to determine what the appropriate level for production usage is.

**Comment by k-wall** [comment]
603ff12f enabled the leak detection annotation on the FilterIT test.  Should we be doing that across all the ITs tests?

**Comment by SamBarker** [comment]
yeah we should @k-wall
