### ISSUE TITLE
Deptective command fails with java 17

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#220]
**Describe the bug**
The architecture check doesn't work with java 17+ 

**To Reproduce**
1. use JDK 19
2. run `mvn clean verify -Dquick -Parchitecture-check -pl kroxylicious` as documented in README.md
3. build fails with:
```
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project kroxylicious: Compilation failure -> [Help 1]
```
Debugging into it I found the `javac` call emits:
```
Exception in thread "main" java.lang.IllegalAccessError: class org.moditect.deptective.DeptectivePlugin (in unnamed module @0xe25b2fe) cannot access class com.sun.tools.javac.api.BasicJavacTask (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.api to unnamed module @0xe25b2fe
```
and there is an open [issue](https://github.com/moditect/deptective/issues/104) upstream for java 17 support.

**Expected behavior**
The command succeeds.

**Additional context**
The README.md also states this is for `for monitoring its architecture and fails any violations`, which doesn't appear to be in the automation and I imagine nobody has run it for a while since it doesn't work with 17+. Should we remove this from the build?

**Comment by k-wall** [comment]
+1 to removing it from the build
