### ISSUE TITLE
Javadoc additional dependency for databind 

### ISSUE THREAD

**Issue by SamBarker** [kroxylicious/kroxylicious#229]
This is rubbish for a few reasons:

1. AFICT we shouldn't need databind on the class path as we should only generate javadoc for `src/main`
2. `databind` is already on the test classpath 
3. The class that fails javadoc generation is in `target/generated-test-sources/` so it possibly implies that we have `target/generated-test-sources/` on the production classpath
4. `additionalDependecies` doesn't resolve via the `dependencyManagment` section so it misses the bom and thus requires an explicit version.

_Originally posted by @SamBarker in https://github.com/kroxylicious/kroxylicious/pull/228#discussion_r1148687254_

**Comment by SamBarker** [comment]
FYI @k-wall maybe one of those observations sparks a thought for you as to how to fix it properly

**Comment by robobario** [comment]
Debugging around I found that the `AbstractKrpcGeneratorMojo` [adds it's output dir as a compile source root](https://github.com/kroxylicious/kroxylicious/blob/5edf2c18e761f7ac30d8a7b0b2468801b8ec94c2/krpc-code-gen/src/main/java/io/kroxylicious/krpccodegen/maven/AbstractKrpcGeneratorMojo.java#L80). The javadoc plugin picks up all [the compile source roots](https://github.com/apache/maven-javadoc-plugin/blob/931164d0c5d11b4ac4559ada68ee5fba1d0df4f6/src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java#L1736).

We should make it configurable whether the KrpcGeneratorMojo is generating test or compile source roots.
