### ISSUE TITLE
Filters cannot intercept SASL requests

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#261]
**Describe the bug**
If a user implements `SaslAuthenticateRequestFilter` or `SaslHandshakeRequestFilter` their filter request code is not hit because the `SaslDecodePredicate` currently [always decides](https://github.com/kroxylicious/kroxylicious/blob/3894a79d68dc28020126ef91548d41fadfb3e9df/kroxylicious/src/main/java/io/kroxylicious/proxy/internal/SaslDecodePredicate.java#L55) not to decode `SASL_HANDSHAKE` or `SASL_AUTHENTICATE`. (handleSasl is always `false` at the moment as KafkaProxy [configures the initializer with an empty map](https://github.com/kroxylicious/kroxylicious/blob/3894a79d68dc28020126ef91548d41fadfb3e9df/kroxylicious/src/main/java/io/kroxylicious/proxy/KafkaProxy.java#L161) of SASL mechanisms)

Maybe the logic should be an or. We decode if a filter targets these APIs or we have SASL mechanisms configured.

**Comment by k-wall** [comment]
Yeah - that seems like a bug to me.  I see the ability to intercept the Sasl RPCs as important for some use cases.
