### ISSUE TITLE
Filter API: improve filter interfaces

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#268]
## Current State

Currently if I want to only intercept specific apiVersions for an RPC I would have to implement the per-message Filter interface and override the `shouldDeserialize[Request|Response]` method of `KrpcFilter`. I would have to be careful to support all the per-message interfaces implemented by the class.

I can shoot myself in the foot by over-riding `shouldDeserialize[Request|Response]` on a per-message Filter telling it to deserialize messages that would cause a class cast exception in the `on[Request|Response]`.

I can shoot myself in the foot by creating a per-message filter and then override `on[Request|Response] to not call the per-message methods I've implemented.

## Ideas

I think we should break this dependency where the individual Message filters obtain invocation logic by extending KrpcFilter. The per-message filters should not extend `KrpcFilter`, or `KrpcFilter` should just become a marker interface. We should move invocation out of the filter-api and into `kroxylicious` so it's the framework's job to do the `instanceof` and invocation rather than the filter.

One idea from Tom's invocation branch is to use annotations to declare what `apiVersions` we want to deserialize for each method. Alternatively we could generate methods like `shouldDeserializeAllocateProducerIdsResponse(short apiVersion)` that default to true on each of the per-message interfaces so we could customize each.

To support writing filters that intercept all ApiMessages maybe we could introduce RequestFilter and ResponseFilter interfaces.

**Comment by k-wall** [comment]
I need to digest your idea more, but one quick comment.

> To support writing filters that intercept all ApiMessages maybe we could introduce RequestFilter and ResponseFilter interfaces.

For multi-tenant, we will want to prefix the clientid with the tenant key.  Clientid is carried by every RPC.  It'd be nice not to have to implement every handler to do this.  I think what you are suggesting here offers the flexibility we need to do this.

**Comment by k-wall** [comment]
I agree with your criticisms identified by "Current State" and like the sound of your ideas.  I think it is worth exploration.
