### ISSUE TITLE
Metrics: make granularity of kroxylicious_payload_size_bytes configurable

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#275]
**Is your feature request related to a problem? Please describe.**
When we introduce virtual cluster as a metrics dimension `proxy * virtualCluster * apiKey * apiVersion` could add up to a lot of time series and users may not be interested in the apiVersion. 

**Describe the solution you'd like**
Enable users to control what granularity to record the metric at, so they can specify whether the finest granularity is apiKey or apiVersion.

Options:
1. consider this an 'application' configuration, so it would not be part of the existing `micrometer:` configuration block. so we add some configuration like:
```
metrics:
  granularity: 'APIKEY|APIVERSION'
```
2. Control it with micrometer configuration. Micrometer can replace the tags of metrics registered with it, so we could potentially add something like:
```
    micrometer:
    - type: "RemoveTags"
      config:
        tagNames:
        - "api_keys"
```
Or go to more detail allowing it to target metrics by name

If we can do something like option 2 it might be nicer, then the application doesn't have to decide what's allowed or conditionally change tags.

**Comment by showuon** [comment]
Triaged on July 31, 2024: Let's close it and wait until real case reported from users to reopen it.
