### ISSUE TITLE
Enable users to control pre-registration of metrics

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#276]
**Is your feature request related to a problem? Please describe.**
Currently we do not pre-register all metrics (payload size summary is not pre-registere). This is because there are numerous combinations of apiKey and apiVersion, combined with virtual cluster granularity it could result in a large number of timeseries being scraped despite only a small fraction of them being used. They are currently registered on-demand when the first payload of that type is decoded. This means that if a user found a way to alert on the increase of one of these metrics, there would be issues with [data correctness](https://github.com/strimzi/strimzi-canary/issues/215) 

**Describe the solution you'd like**
Users can control pre-registration of metrics, perhaps with a whitelist or blacklist of metrics. This would be part of the "application" responsibilities rather than the generic micrometer configuration (because micrometer cannot control when or why we are registering the metrics) so this might need a new configuration block like:

```
metrics:
    pre-register:
        include: 
        - ".*"
        exclude:
        - "kroxylicious_payload_size_bytes"
```

**problem**
Should filter authors be responsible for pre-registration of their own metrics? Should we expose this kind of configuration to Filters? Or we could stop using the global micrometer registry and try to implement this lazy/eager registration in our own implementation of a registry. For example in the counter case it could return a `io.micrometer.core.instrument.Counter` that doesn't register the metric with the underlying prometheus registry until the first call to `increment` (or in the eager case it would behave normally).

**Comment by showuon** [comment]
Triaged on July 31, 2024: Let's close it and wait until real case reported from users to reopen it.
