### ISSUE TITLE
Fix FilterInvoker javadoc

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#322]
I think it's worth a follow up PR since it's raised questions here and in the initial PR adding it. We decided that it was a better interface if the `FilterHandler` could call `onRequest` or `onResponse` and have the invoker decide what to do with it even if it isn't interested in that particular decoded message. But I see now we've got a mismatch in the `FilterInvoker` javadoc where it says:

```
Handle deserialized request data. It is implicit that the underlying filter wants to handle this data
...
default void onRequest(...)
```

We should update the javadocs to say that `onRequest` and `onResponse` can be called for any decoded message and the Invoker implementation should handle forwarding if it's not interested in that particular decoded message.

_Originally posted by @robobario in https://github.com/kroxylicious/kroxylicious/pull/320#discussion_r1195900830_

**Comment by k-wall** [comment]
@robobario please check whether the issue is still valid.

**Comment by robobario** [comment]
Yes it's still valid. 

The javadoc implies `onRequest` and `onResponse` of the FilterInvoker will not be called if the FilterInvoker has indicated it does not handle that ApiKey + version.

We changed the logic at some point so that if any FilterInvoker in the chain wants to intercept that `(ApiKey, Version)` then all invokers in the chain will have their `onRequest` and `onResponse` invoked and it's up to the implementation to do a simple forward if they receive a decoded message they aren't interested in (currently implemented by SafeInvoker).

I think the only real issue is in the docs. I'll remove the bit about the refactoring.
