### ISSUE TITLE
Containerise Kroxylicious

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#335]
We want to demonstrate Kroxylicious running on kubernetes. To do this we need a container image. 

Some options are:
1. use [jib](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin) to emit a container image as part of the maven build.
2. add a `Dockerfile`

Note Kroxylicious has a quay.io account, so scripts to push released images there would be handy, access to images in a public repository makes it easier to test things on minikube.

**Comment by k-wall** [comment]
I'll need this soon too.  I want to start experimenting/documenting Kroxylicious deployment topology, so having a repeatable container image is a must.

**Comment by robobario** [comment]
Implemented in #364
