### ISSUE TITLE
Sample Filter project

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#336]
As a community Filter Author or new contributor I want to be able to see a sample filter project to understand what features are available.

**Describe the solution you'd like**
I can obtain an example Filter project that:
1. Has integration tests (see the likes of JsonSyntaxValidationIT or KrpcFilterIT)
2. Has unit tests
3. Has a filter implementation that does something with produce or consume data, for example uppercasing all data produced.
4. Uses a jackson configuration object to pass configuration about the filter (see `FixedClientIdFilterConfig` and `TestFilterContributor` for an example)
5. Uses micrometer to record some metric

This could be from a github template repository, or live in the main kroxylicious repository, or something else?

**Comment by gracegrimwood** [comment]
Done in #399
