### ISSUE TITLE
Extract shared (global) filters, e.g. for name mappings

### ISSUE THREAD

**Issue by gunnarmorling** [kroxylicious/kroxylicious#36]

**Comment by gunnarmorling** [comment]
// CC @tombentley

**Comment by k-wall** [comment]
We have filters at the top level of the configuration, and they apply equally to all virtual clusters.  So I believe the issue is answered.

(What we can't do at the moment is have a different filter list applied to different virtual clusters, but we don't currently have a use-case for that).
