### ISSUE TITLE
portNumber pattern is superfluous in PortPerBrokerClusterNetworkAddressConfigProvider

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#412]
`PortPerBrokerClusterNetworkAddressConfigProvider` currently requires that brokerAddressPattern is a string in the form:

`host:$(portNumber)`

The replacement token `$(portNumber)` seems superfluous.  We could just define `brokerAddressPattern` as providing the `host` portion only.  The mechanics of the `#getBrokerAddress` can build the broker's using the HostPort(host, port) constructor.  It doesn't need substitution.

At the moment the implementation allows weird things like: `host:9$(portNumber)`, which really was never intended.

https://github.com/kroxylicious/kroxylicious/blob/bd6e7b1bda023a5f9d1010f58460689024031838/kroxylicious/src/main/java/io/kroxylicious/proxy/internal/clusternetworkaddressconfigprovider/PortPerBrokerClusterNetworkAddressConfigProvider.java#L110C128-L110C147

Any objections to refactoring brokerAddressPattern to be a host name pattern only?

**Comment by SamBarker** [comment]
It seems reasonable to remove port number to me. I think simplifying the pattern to just define the hostname make sense. 

The only reason not to I can think of a corner case of is people wanting to do something like `broker-1-${portNumber}:${portNumber}` as a way of identifying the listener. 

So I'm +1 to simplifying and removing port number.

**Comment by robobario** [comment]
+1 to removing it

**Comment by k-wall** [comment]
Thanks for the comments.  I'll do that.
