### ISSUE TITLE
Document advanced filter behaviours

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#420]
The filter documentation already describes the basic work of a filter chain and the protocol filters, where each request follows through A -> B -> C and each response flows back to through C -> B -> A.  What we are missing is documentation
describing the other abilities of the filter:

1. request filters can, at their own volition. send their own response (i.e. an error response).
2. filters can make their own requests to the broker

etc.

_Originally posted by @k-wall in https://github.com/kroxylicious/kroxylicious/pull/406#discussion_r1244948459_

**Comment by robobario** [comment]
Keen to do this
