### ISSUE TITLE
Run Kafka system tests with Kroxylicious

### ISSUE THREAD

**Issue by SamBarker** [kroxylicious/kroxylicious#426]
**Describe the solution you'd like**
As part of validating Kroxylicious as a transparent proxy service we should be able to inject a Kroxylicious instance in the middle of the client connections in the Kafka system tests and they still pass (assuming a stable set of system tests).

We would probably want to run this exercise as part of bumping the Kafka-clients version we depend on as part of our release process.

**Comment by gracegrimwood** [comment]
Triaged 22 November 2023: needs further discussion, concerns were raised about this.
