### ISSUE TITLE
Remove `assert` statements

### ISSUE THREAD

**Issue by gunnarmorling** [kroxylicious/kroxylicious#45]
Either truly enforce the invariant also at runtime, or don't. As assertions are not enabled in many production environments, they represent some odd go-between.

**Comment by gunnarmorling** [comment]
May also forbid them via Checkstyle.

**Comment by satyamsaxena2001** [comment]
@gunnarmorling can you reiterate here what is to be done here.I am willing to start off with the issue.

**Comment by gunnarmorling** [comment]
Hey @satyamsaxena2001, as I'm not actively involved with the project any longer, I recommend you touch base with @tombentley / @k-wall / @SamBarker on this.

Personally, I don't see much value in having asserts and thus had suggested to remove them. Also see the discussion in #77, at some point there was the idea to keep assertions for documenting assumptions made e.g. in private methods, relying on the test suite to run with assertions enabled. I'm not sure whether consensus was reached eventually and if so, how that looks like.

**Comment by tombentley** [comment]
@satyamsaxena2001 thanks for your interest! This might not be the best first contribution. We struggled to reached a consensus about `assert`. If you're interested in contributing to the project generally then we can try to find a few beginner-friendly issues for you to get started.

**Comment by SamBarker** [comment]
Hey @satyamsaxena2001 if my memory serves me the discussion around `assert` got a lot more nuanced but we forgot to remove the `easy-starter` label from issue (I've fixed that now).

**Comment by satyamsaxena2001** [comment]
@tombentley yes, i would love to contribute.
