### ISSUE TITLE
Tidy up utility methods for MultiTenantIT

### ISSUE THREAD

**Issue by gracegrimwood** [kroxylicious/kroxylicious#450]
Per [Keith's comment](https://github.com/kroxylicious/kroxylicious/issues/349#issuecomment-1623342805) in #349 (Split up MultiTenantIT test):

> we've also been building up lots of utility methods (createTopic, deleteTopic etc) across the IT suite. It might make sense to bring some order to those first (under a separate issue), then you can reuse those with the separate MultiTenant IT tests.

Need to tidy up these methods before progressing with #349

**Comment by k-wall** [comment]
Might be worth looking more widely than MultiTenantIT (suggest **/*IT.java).  We've  got helper methods such as `#createTopic` coming up like weeds 🌿!

**Comment by gracegrimwood** [comment]
Addressed in #490
