### ISSUE TITLE
Documentation accidentally a word?

### ISSUE THREAD

**Issue by LiamClarkeNZ** [kroxylicious/kroxylicious#452]
https://github.com/kroxylicious/kroxylicious/blob/d04574562629b172c1baced9e7be517c6396f321/README.md?plain=1#L96

> We bind checkstyle to the `verify` phase of the build so `mvn clean verify` will

It ends at `will` but I'm pretty sure there's supposed to be more words after it.

**Comment by SamBarker** [comment]
doh! thanks for the heads up @LiamClarkeNZ
