### ISSUE TITLE
Integration tests sometimes fail on instantiating IntegrationTestInetAddressResolverProvider

### ISSUE THREAD

**Issue by gracegrimwood** [kroxylicious/kroxylicious#486]
**Describe the bug**
Integration tests sometimes fail with `java.util.ServiceConfigurationError: java.net.spi.InetAddressResolverProvider: Provider io.kroxylicious.net.IntegrationTestInetAddressResolverProvider could not be instantiated`. This looks to be because the `LoggerFactory#getLogger` call during instantiation of `IntegrationTestInetAddressResolverProvider` is attempting to resolve its own hostname, but cannot because we have not yet instantiated `IntegrationTestInetAddressResolverProvider`. A bit of a catch-22.

**To Reproduce**
1. Run `mvn clean install -pl integrationtests`
2. Sometimes the first test will fail right at the start with `java.util.ServiceConfigurationError: java.net.spi.InetAddressResolverProvider: Provider io.kroxylicious.net.IntegrationTestInetAddressResolverProvider could not be instantiated` and all subsequent tests will then fail.

I've only managed to produce this error on my [WIP branch](https://github.com/gracegrimwood/kroxylicious/tree/multitenantit-util-methods-450), but the code in question has not been changed in that branch.

**Expected behavior**
`IntegrationTestInetAddressResolverProvider` should instantiate without failing.

**YAML files and logs**

Logs are in [this gist](https://gist.github.com/gracegrimwood/9c2509274b64b1e21f1e18b7a7030208).

**Comment by SamBarker** [comment]
So my working theory is the bug exists on main but we get away with it. As it seems like the problem is todo with initialising log4j. During initialisation log4j attempts to determine its hostname which fails as the logger being initialised is in the dns resolver we use for tests.

@gracegrimwood tried adding a logger to the new base class everything works again. I suspect this is because logging is initialised satisfactorily before the resolver tries to log

**Comment by SamBarker** [comment]
@k-wall i wanted to make sure this one was on your radar. 

Is the logger in the resolver worth having ? Or should we try and initialise it lazily and or defensively?

**Comment by k-wall** [comment]
Oh, I hadn't seen this issue before.  I don't really think we lose much by removing the logging from this class.
