### ISSUE TITLE
Rename classes, removing Krpc prefixes.

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#517]
In #494 we had some discussion about whether the Krpc prefixes made sense, but held off on renaming them since it was a big branch already. So it would be good if we could rename things like `KrpcFilter -> Filter`, `KrpcFiIterContext` -> `FilterContext`. Now's the time while we are already breaking the Filter APIs significantly :)

Also keen to revisit the naming of `FilterResult` as that is often used to mean 'value-or-exception' so could be a bit misleading. I though `FilterCommand` might be good, indicating it's something the FilterAuthor is commanding Kroxylicious to do, and then the framework executes it.

**Comment by xerox78** [comment]
Hi, would like to contribute, is this issue still available ?

**Comment by SamBarker** [comment]
Hey @xerox78 your welcome to have a go and open a pull request. 

Please do let us know if you need any help.

**Comment by robobario** [comment]
Hi @xerox78, are you still interested in this one? We're keen to have this change in before we release 0.3.0

**Comment by robobario** [comment]
I've picked up the Krpc prefix removal work

**Comment by SamBarker** [comment]
Fixed in https://github.com/kroxylicious/kroxylicious/pull/591
