### ISSUE TITLE
Async chaining methods #xxxxAsync of InternalCompletionStage run on JDK thread rather than Netty thread

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#537]
The filter documentation includes the following words:

https://github.com/kroxylicious/kroxylicious/blob/b255d2e6cd0400ed973c3bb60ff1173cdff00a6d/docs/custom-filters.adoc?plain=1#L441C110-L443C15

```
Note that this stage is completed on the same thread as the rest of the Filter work, so we can safely mutate Filter members without synchronising.
```

Whilst this is true in the case of *non-async* chaining (`thenApply` etc) to`context.sendRequest`, in the case on asynchronous chaining (`thenApplyAsync`), this is not the case.  If the user were to try to update filter members from with such an action, that update will not be published safely between threads.

###  *non-async* chaining (safe publication)
```java
        return context.sendRequest(version, ....)
                      .thenCompose(asyncResponse -> {
                           // This is safe - we are on netty thread
                           this.myFilterList.add(..)
                           return context.forwardRequest(header, request));
                      }:
    }
```

###  async chaining (unsafe publication)
```java
        return context.sendRequest(version, ....)
                      .thenComposeAsync(resp -> {
                           // Unsafe - we are on a ForkJoinPool thread
                           this.myFilterList.add(..)
                           return context.forwardRequest(header, request));
                      }:
    }
```

**Comment by k-wall** [comment]
I think the InternalCompletionStage should take the executor from Netty, then use this to run the async tasks.

**Comment by k-wall** [comment]
I think for correctness:

* the completed CompletionStage produced by the FilterContext factories should be configured with the Netty executor too.  This means is the filter calls `stage.thenApplyAsync(() -> {mutate filter state})` everything still works.
  
* we should consider offering a `FilterContext.newCompletableFuture` which is pre-wired to the Netty executor.  Filter Authors should use in their async work in preference to calling `new CompletableFuture()`.  Work carried out using actions chained to this future would be have the same thread safety guarantees (i.e. could mutate state).

Do we need to note in the documentation to warn Filter Authors who bring their own futures that the thread safety guarantees doesn't apply?  OTOH that's just plain old Java.

We should add FilterHandlerTests that verify actions take place on the executor we expected.

**Comment by gracegrimwood** [comment]
Triaged 16/08/23 - existing PR is a good short-term fix, discussion needed for long-term solution.
