### ISSUE TITLE
SampleFilterTransformer drops the headers

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#548]
_Please use this to only for bug reports_. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/kroxylicious/kroxylicious/discussions) or use the [community Slack](https://kroxylicious.slack.com) chat.

**Describe the bug**

I notice that `SampleFilterTransformer` is silently dropping the message headers, it probably shouldn't.  It is likely that the sample code will be used as a basis for filter authors implementations, so this might be a source of a bug in someone else's code.

https://github.com/kroxylicious/kroxylicious/blob/5eebb43240fcacbdaec289ea1fe04611a0015cf0/kroxylicious-sample/src/main/java/io/kroxylicious/sample/util/SampleFilterTransformer.java#L66

**To Reproduce**
1. Configure kroxylicious like this ...
2. Run command '....'
3. See error

**Expected behavior**

**YAML files and logs**

Attach or copy paste your kroxylicious configuration YAML (with sensitive details
like broker address redacted).
Attach or copy and paste relevant logs.

**Additional context**

**Comment by gracegrimwood** [comment]
Triaged 16/08/23
