### ISSUE TITLE
Tidy up DEV_GUIDE shell examples and document additional filters profile

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#552]
> We've got a bit of inconsistency with placeholders in the text.  We've got curly brackets here and dollars used down below `$your_quay_username$` etc.  We should use a single style.  I don't care which.

_Originally posted by @k-wall in https://github.com/kroxylicious/kroxylicious/pull/542#discussion_r1293108667_

**Comment by robobario** [comment]
Also we should document the withAdditionalFilters profile https://github.com/kroxylicious/kroxylicious/pull/542#issuecomment-1676907307

**Comment by gracegrimwood** [comment]
> We've got a bit of inconsistency with placeholders in the text. We've got curly brackets here and dollars used down below $your_quay_username$ etc. We should use a single style. I don't care which.

My vote is for something that actually works for variable substitution in the terminal, i.e. `$My_Awesome_Variable`. That way if I want to I can set `$My_Awesome_Variable` to whatever my substitute value is in my terminal, then paste in the command as-is and not have to edit it to make it work.

**Comment by gracegrimwood** [comment]
Triaged 16/08/23
