### ISSUE TITLE
Revisit intellij gitignores (.iml files from deleted modules continue to re-appear)

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#553]
> The phantom iml. We should revisit if we can switch to a more typical idea gitignore now.

_Originally posted by @robobario in https://github.com/kroxylicious/kroxylicious/pull/538#discussion_r1294045852_

We often see the `api/kroxylicious-api/kroxylicious-api.iml` return to haunt us.

We should revisit if there are some IDEA files that should be gitignored. 

We are trying to make sure that it's easy to run our project in Intellij which is tricky because of our compiler setup where most modules use 17 and integrationtests uses 20.

Also we want to have the IDEA code formatting and import order checked in so we aren't battling with checkstyle and the maven plugins that format the code.

But maybe we don't need to check in the imls?

**Comment by SamBarker** [comment]
Updating the `.gitignore` to remove `*.iml` and friends is possible and dropping them from the checkout is possible. However it comes with a couple of caveats. Namely

1. Users have to use Maven auto import in Intellij. 
2. Once we merge the change removing the `*.iml` files everyone will have to re-import their projects. 

I'm +1 to doing that but wanted to flag it before proceeding.

**Comment by k-wall** [comment]
+1 to dropping them.

**Comment by gracegrimwood** [comment]
+1 to this, would be nice to not have to manually exclude `*.iml` files from every commit.

**Comment by gracegrimwood** [comment]
Triaged 16/08/23
