### ISSUE TITLE
Add log4j2 configuration and license to binary distribution

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#555]
As a user I want to configure the log level of Kroxylicious when using the binary distribution so that I can debug and understand what it is doing. Currently log4j2 is configured by a default configuration bundled in the jar, we should bundle a file in the distribution and configure the application to load it with a system property.

It would also be good to bundle our license in the distribution, maybe also some metadata about what commit it was built with. Or we could include the commit hash/ref in the metadata.properties of `kroxylicious-app` and make it part of `kroxylicious-start.sh --version`

**Comment by gracegrimwood** [comment]
Triaged 16/08/23
