### ISSUE TITLE
Document thread thread safety etc in javadoc.

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#557]
As a Filter Author, I need to understand what thread rules apply to the API.  We have some words in the Asciidoc already, but we probably want the content in the Javadoc too.  It probably belongs in the package-info.java file so it can be referenced from class level documentation.

_Originally posted by @SamBarker in https://github.com/kroxylicious/kroxylicious/pull/544#discussion_r1294138256_

              We should probably have some text here about:

- Thread safety
- The fact that filter instances are scoped to a specific client connection
- Maybe something about sharing state?

 Potentially could be left to an alternate PR.

**Comment by gracegrimwood** [comment]
Triaged 16/08/23 - should document as we go, once shared state, etc. is figured out we can document that but we should have reference to current state for now.

**Comment by k-wall** [comment]
I've taken steps towards this in #617. I believe I've covered everything described the description.
