### ISSUE TITLE
Give SafeInvoker the responsibility to valid that the filter didn't return null

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#558]
tempted to say we should extract a method `safeInvokeResponse`hmm naming isn't great. Or maybe we should be pushing the null checking into the SafeInvoker so that it will always return a stage?

_Originally posted by @SamBarker in https://github.com/kroxylicious/kroxylicious/pull/538#discussion_r1294068333_

**Comment by gracegrimwood** [comment]
Triaged 16/08/23
