### ISSUE TITLE
Automate attaching binary distribution to GitHub release

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#559]
Currently we build and release the libs wlto maven central, and then tag the commit as vX.Y.Z and create a matching GitHub release.

Now that we can create binary distributions we should attach the tarball and zip to the release. Then we could point users towards the GitHub release to download it.

This would involve running another maven command with the dist profile and then I'm guessing some gh commands to attach the binaries after creating the release.

**Comment by gracegrimwood** [comment]
Triaged 16/08/23

**Comment by tombentley** [comment]
@robobario was this done for 0.3.0? Or should it be moved to 0.4.0?

**Comment by robobario** [comment]
> @robobario was this done for 0.3.0? Or should it be moved to 0.4.0?

Please move to 0.4.0, I don't see any distributions attached to 0.3.0 so assume this hasn't been touched

**Comment by gracegrimwood** [comment]
fixed by #776
