### ISSUE TITLE
Implement context.sendRequest()

### ISSUE THREAD

**Issue by tombentley** [kroxylicious/kroxylicious#56]
Sometimes filters need to make requests of their own, and have the response delivered to them. 

Topic Encryption provides an example of this when the topic encryption key depends on the topic name but the fetch response is version >=13  and so contains topic ids rather than names. Obviously such a filter needs a way to look up the name corresponding to the id it observes. Due to the nature of the Kafka protocol we can't rely on a filter instance observing metadata responses to the client as a way of populating such a lookup (because the request could, in general, be sent via another proxy instance). Nor can we rely on doing this at proxy startup (because topics can be created after then). The only way to do it is for the filter to be able to do the lookup for itself.

Per the discussion in #53, for filters to still compose nicely, the upstream filters should be applied to the request and the response, but the response should not propagate beyond the originating filter (nor should the client should see them).

**Comment by gunnarmorling** [comment]
@tombentley, any more things you'd like to attribute to this one? Or can we resolve it?

**Comment by gunnarmorling** [comment]
Btw. issues are auto-closed if you put a comment like "Fixes #123" to a PR.

**Comment by tombentley** [comment]
Happy to close this one
