### ISSUE TITLE
Integration test production artifacts

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#599]
**Is your feature request related to a problem? Please describe.**
We have been working on a binary distribution (#424) and want to offer a production-grade docker image (#597). We need some confidence that we aren't breaking these distributions as we make changes.

**Describe the solution you'd like**
The binary distribution and docker images have testing automation, ideally run against PRs, but at least run against main after merge.

**Comment by tombentley** [comment]
Triaged 2023/11/08: We should aim to do this in by the next release.

**Comment by SamBarker** [comment]
This task should include raising additional task for missing integration/system tests that we need for 0.5.0 milestone.

**Comment by k-wall** [comment]
We think that the system tests, which will be testing the container images built by the github actions, cover the requirements set out by this issue.
