### ISSUE TITLE
Proper disconnect handling

### ISSUE THREAD

**Issue by gunnarmorling** [kroxylicious/kroxylicious#6]
Follows up on #3; for now, we can simply fail eagerly and stop the proxy if we loose the backend connection. In subsequent steps we can consider to implement re-connects within the proxy.

// CC @franz1981

**Comment by gunnarmorling** [comment]
We should also add a test for this, stopping the backend Kafka broker and assert the resulting exception in the proxy.

**Comment by robobario** [comment]
closing stale
