### ISSUE TITLE
Document how to configure logging

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#600]
**Suggestion / Problem**
Adminstrators will need guidance on how to:
1. customise the log4j config
2. increase the kroxylicious log level

**Comment by robobario** [comment]
Repurposed to capture one thing I think is useful. The rest was rotten or too ambiguous to be picked up.

**Comment by showuon** [comment]
@robobario , please create a new issue for another one.

**Comment by showuon** [comment]
@robobario , please create a new issue for another one.
