### ISSUE TITLE
Ability to discover why a filter closed a connection

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#629]
We have a number of use-cases where a filter may cause the connection to be closed.  This includes exception cases where errors in the filter implementation propagate exceptions back to Kroxylicious.

At the moment the only way to discover why a connection was closed is to read the log.

 It would be useful to have an API  that exposed this information to the Filter Author.

This would also allow for stronger tests.

_Originally posted by @SamBarker in https://github.com/kroxylicious/kroxylicious/pull/625#discussion_r1335243825_

**Comment by gracegrimwood** [comment]
Triaged 1 Nov 2023 - not a priority, closing this.
