### ISSUE TITLE
Integration tests should rely on JDK 21 (LTS) rather than 20.

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#634]
Now JDK 21 is available, Kroxylicious integration tests should rely on it rather than JDK 20.
The project production dependency remains at JDK 17 (LTS).

**Comment by k-wall** [comment]
`sdk install java 21-tem` is not yet available.  Let's wait a few more days.

**Comment by k-wall** [comment]
@SamBarker https://adoptium.net/en-GB/temurin/releases/ still says awaiting test specification.

**Comment by SamBarker** [comment]
We could switch which distribution of the jdk we us in the actions? Or wait I don't think there is a rush.

**Comment by SamBarker** [comment]
Also is there any reason to leave the production sources at 17? Jdk21 is LTS as well iirc

**Comment by k-wall** [comment]
Checking I understand the intent of the project: keep the production binanies JDK 17 compatible.

You mean keep `maven.compiler.target` at 17 for modules other than integrationtests but use `maven.compiler.source` 21 across the whole project? I suppose that should work.  I suppose there's the risk that JDK 21 language features creep into our examples, which might confuse a Filter Author.

Yes, JDK 21 is LTS.

**Comment by SamBarker** [comment]
I'm not sure there is a need to keep the binary version at 17 either...

**Comment by k-wall** [comment]
..
