### ISSUE TITLE
Refactor: Rename kroxylicious module to kroxylicious-runtime

### ISSUE THREAD

**Issue by tombentley** [kroxylicious/kroxylicious#637]
It's confusing having a module named kroxylicious. It makes is harder to know if someone is referring to the module, or the project. If someone talks about "the runtime" its harder for someone to figure out which module that refers to (or that it refers to a module).

**Comment by SamBarker** [comment]
+1

**Comment by gracegrimwood** [comment]
Triaged 1 Nov 2023 - once the big PR currently open (#667) is merged, let's get this done.

**Comment by k-wall** [comment]
There were some ideas expressed on #610 about other module renames for consistency.

## Test support modules.

kroxylicious-test-tools -> kroxylicious-integration-test-support
kroxylicious-unit-test -> kroxylicious-test-support

## Naming convention for filter modules.

kroxylicious-multitenant -> kroxylicious-filter-multitenant
kroxylicious-schema-enforcement` kroxylicious-filter-schema-enforcement

# Integration tests
integrationtests -> kroxylicious-integration-tests
