### ISSUE TITLE
Generate builders for config api?

### ISSUE THREAD

**Issue by tombentley** [kroxylicious/kroxylicious#639]
(Some of) the config api classes have hand-written builder classes. We should look at generating these using something like sundrio. We might want to factor the config api into a separate module to do this.

**Comment by zemjak** [comment]
What about using an annotation to match config classes (sth like @Builder) and then filter those classes with annotation processor [javadoc](https://docs.oracle.com/javase/8/docs/api/javax/annotation/processing/Processor.html), and generate .java code with [apache velocity](https://velocity.apache.org/) template?

**Comment by tombentley** [comment]
That's exactly what [sundrio](https://github.com/sundrio/sundrio) does (except without the Velocity part). It's nicer than using something like lombok because it operates purely as an annotation processor without downcasting into the compiler's internal AST representation.

**Comment by gracegrimwood** [comment]
Triaged 1 Nov 2023 - not a priority, closing this.
