### ISSUE TITLE
Move internal classes out of kroxylicious-api

### ISSUE THREAD

**Issue by tombentley** [kroxylicious/kroxylicious#640]
The following are types in the api module which I'm not sure should be part of the public API:

* FilterAndInvoker
* FilterInvoker
* FilterInvokers

AFAICS how filter get invoked should not be part of the api, but part of the runtime.

edit: These are now eligible to be moved since they were deprecated in 0.3.0

**Comment by gracegrimwood** [comment]
Triaged 1 Nov 2023 - nice to have, not a priority.
