### ISSUE TITLE
Reevaluate ApiVersionsService

### ISSUE THREAD

**Issue by tombentley** [kroxylicious/kroxylicious#641]
* It's not entirely clear why we need a separate interface for this. The method could be declared in the FilterContext seemingly with losing anything
* If a separate interface is warranted it should be in io.kroxylicious.proxy.filter
* It's also not clear why we need to expose both `upstream` and `intersected`. All a filter should really know is what API versions are can be used when sending requests to the next thing in the chain (be that filter or real broker). An upstream filter might have narrowed the range of versions by intercepting `ApiVersions`. Letting a filter see anything other than this breaks composability.

**Comment by gracegrimwood** [comment]
Triaged 1 Nov 2023 - ApiVersionsService is deprecated, will be removed (not a priority). Will keep this issue until it is removed.

**Comment by robobario** [comment]
This resulted in a deprecation
