### ISSUE TITLE
Enable InvalidFilterConfigurationException to express a list of failure reasons.

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#644]
As part of #623 we introduced InvalidFilterConfigurationException thrown from `validateConfiguration(config)` on the `FilterFactory`. This enables FilterFactory to do custom validation of configuration semantics.

Currently the constructor only enables you to pass a message String, or a message String plus Throwable.

It is easy to imagine a Filter finding a Collection of failures for their config so we thought it would be nice to give the User some convenient way to build an InvalidFilterConfigurationException from a list of failure Strings.

One way could be adding constructors like `InvalidFilterConfigurationException(String ... failures)` or `InvalidFilterConfigurationException(Iterable<String> failures)` and building up a pretty error message from that.

**Comment by tombentley** [comment]
`String...` is probably less useful than it might appear from toy examples. If you're going to code `validateConfiguration()` in a fail-at-the-end style then you're most likely to use a mutable collection of errors that you add stuff to, and throw at the end if it's non-empty.

It's also worth thinking how much value this really adds. If we're just going to log it, or `System.exit(1)` or whatever then all this gets us is a consistent was of joining the multiple errors, right? It's only if we're going to do something more than report all of them that this starts to become useful. And that probably requires something more sophisticated than a `String` as the `Set` element?

**Comment by SamBarker** [comment]
> `String...` is probably less useful than it might appear from toy examples. If you're going to code `validateConfiguration()` in a fail-at-the-end style then you're most likely to use a mutable collection of errors that you add stuff to, and throw at the end if it's non-empty.
> 
> 
> 
> It's also worth thinking how much value this really adds. If we're just going to log it, or `System.exit(1)` or whatever then all this gets us is a consistent was of joining the multiple errors, right? It's only if we're going to do something more than report all of them that this starts to become useful.

Having been on the receiving end of many a system that failed at the first config error, I'd really value something that collected all the errors and logged them. 

We can revisit the internal element later if we want to try and do something more sophisticated.

**Comment by tombentley** [comment]
This API doesn't provide that though. It's still up to the author to code it so they pass more than a singleton. Indeed, no type can guarantee they don't fail fast.

**Comment by SamBarker** [comment]
But if it doesn't accept more than one message we are implicitly saying fail fast, by accepting multiple we ask them to collect errors. We encourage good behaviour even if we can't guarantee it

**Comment by tombentley** [comment]
I don't think a single String parameter implies fail fast. The author is perfectly capable of joining multiple reasons into a single string. They just have to be bothered to do so. The only difference between what you're suggesting and what I'm suggesting is who does the joining.

**Comment by gracegrimwood** [comment]
Triaged 1 Nov 2023 - closing this as it will be looked at as part of dynamic config during runtime.
