### ISSUE TITLE
Upgrade to kafka 3.6.0 kafka-native

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#666]
We want to include kafka 3.6.0 in Kroxylicious 0.3.0, so we want to test against kafka-native once a 3.6.0 image is available.

**Comment by k-wall** [comment]
#665 will bump the IN_VM test path to use Kafka 3.6.0.   Actually, the project started to use Kafka 3.6.0 for any container tests (spontaneously - as the kafka-native image was pushed).
