### ISSUE TITLE
release fails to replace kroxylicious-api.version in BOM

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#671]
**Describe the bug**

The BOM has a maven property [`kroxylicious-api.version`](https://github.com/kroxylicious/kroxylicious/blob/450f49e9f75ac331f72b971837def1278e3523d8/kroxylicious-bom/pom.xml#L25) which is set to a value, `0.3.0-SNAPSHOT.`  There's nothing in the release process that actually sets that variable to the released version.

There is a step in the [`release-api.sh`](https://github.com/kroxylicious/kroxylicious/blob/450f49e9f75ac331f72b971837def1278e3523d8/scripts/release-api.sh#L26) but the capitalisation/punctuation of that variable is different `kroxyliciousApi.version`.

The intent here is not clear.   Do we really mean to have two separate variables?  

**Expected behavior**

**YAML files and logs**

Attach or copy paste your kroxylicious configuration YAML (with sensitive details
like broker address redacted).
Attach or copy and paste relevant logs.

**Additional context**

**Comment by k-wall** [comment]
@SamBarker I'm thinking that we should standardise on `kroxylicious-api.version`.  Is that right?

**Comment by SamBarker** [comment]
Yeah, should definitely be one variable, there was no intent for distinct usage in the different contexts. I'm happy to standardise on `kroxylicious-api.version`
