### ISSUE TITLE
release deploy tries to deploy all modules, even if you are only trying to release the api

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#672]
_Please use this to only for bug reports_. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/kroxylicious/kroxylicious/discussions) or use the [community Slack](https://kroxylicious.slack.com) chat.

**Describe the bug**

Running an API only release  like below, will deploy none API modules too.

```
./release.sh -k 'xxxxxx' -a 0.3.0
```

https://github.com/kroxylicious/kroxylicious/blob/450f49e9f75ac331f72b971837def1278e3523d8/release.sh#L77

I notice there is commented out code

https://github.com/kroxylicious/kroxylicious/blob/450f49e9f75ac331f72b971837def1278e3523d8/scripts/release-api.sh#L37

I wonder if we forgot to refactor this after the BOM was introduced?

**Expected behavior**

I'd expect an API release to just release the API, a framework release should assume that the API release is done already, and just deploy the framework.

**YAML files and logs**

Attach or copy paste your kroxylicious configuration YAML (with sensitive details
like broker address redacted).
Attach or copy and paste relevant logs.

**Additional context**

**Comment by k-wall** [comment]
Let's go back to requirements.  I think we need:

- ability to release the whole thing (api/framework/bom)
- ability to release the framework/bom for bug fixes
- i don't think we need to re-release the api - we'd just roll a new release.

is that right?

**Comment by SamBarker** [comment]
> Let's go back to requirements. I think we need:
> 
> * ability to release the whole thing (api/framework/bom)
> * ability to release the framework/bom for bug fixes
> * i don't think we need to re-release the api by itself - we'd just roll a new release.
> 
> is that right?

I think 1 & 3 are certainly right. As for 2, I'm questioning the need for it. 

Originally as you've outlined I was aiming for the API to be a separately versioned artefact with the goal being to allow it to evolve independently. However during the API stability discussions my thinking has evolved to the point I don't see a need for it have an independent version. 

The API module needs to be independently consumable but it still exists within the context of the proxy runtime. We do not want to try and support people deploying filters with API version 0.3.0 into runtime version 1.3.0 (as usual I'm advocating for pragmatism we shouldn't try to prevent it, we shouldn't aim to support it either).

Versioning the API separately to the runtime is effectively a distributed monolith. All the pain of distribution and few of the benefits. 

So I'm saying we need a single version number to cover all the modules, some of the time even most of the time, the version will change but the content of the artefact will not change. I think thats OK. It still represents a single tested entity with guaranteed compatibility.

**Comment by robobario** [comment]
I'm not following:

>  The API module needs to be independently consumable but it still exists within the context of the proxy runtime.

Each version of the proxy runtime is built and tested against a version of the API module, but why should they move in lockstep? I think it's going to be surprising to users if a jar named `*-api` is changing versions without any change to the api.

Do you have an example in mind of some painful situation caused by releasing kroxylicious-api 0.3.0 and keep releasing new versions of the kroxylicious-runtime that depend on 0.3.0.

**Comment by SamBarker** [comment]
> Each version of the proxy runtime is built and tested against a version of the API module, but why should they move in lockstep? I think it's going to be surprising to users if a jar named *-api is changing versions without any change to the api.

My contention is users don't care that the version changed without the jar changing. They derive no benefit from being the api staying at 0.3.0 when we release 0.3.1 of the runtime. As soon as the runtime and the API versions diverge we have got some explaining to do as to what the compatibility matrix is. 

The other scenario is something along the lines of we make a change to how the runtime validates objects passed through the API. Technically the binary API hasn't changed but the conventions of its usage have. Should that be an API version bump or not? Its certainly a version bump for the runtime and by having them move in lock step we avoid having to ask and answer that question. 

If we version it independently we are incurring all the costs of having to explain compatibility, higher costs to building and releasing, head aches around releasing the bom, how does it point at a new API release but a snapshot of the runtime modules? 

And then I'm questioning the value users derive from independent versioning. Its gone from a cheap and obvious thing to do , for me, to expensive and of dubious value.

**Comment by robobario** [comment]
But what's the story look like then for community contributed Filters. Say I've released my topic-encryption filter to maven central depending on kroxylicious-api 0.30.0, so is it only supported on Kroxylicious 0.30.0 (or run at your own risk)? Do I have to release new versions of this filter for each release of kroxylicious?

**Comment by SamBarker** [comment]
My other thought is that if we are following semver properly our version numbers should be driven by changes to the public API anyway.

> Say I've released my topic-encryption filter to maven central depending on kroxylicious-api 0.30.0, so is it only supported on Kroxylicious 0.30.0 (or run at your own risk)? Do I have to release new versions of this filter for each release of kroxylicious?

If we move from public API version 0.30.0 to 0.40.0 the community supplied filter has to be validated by the person deploying it anyway. If we have a compatibility matrix that validation could just be seen as reading a page, but does that really cut the work? In practice you need to test the filters you want to deploy with the runtime you want to deploy them with. 

I'd really hope its a dependabot type trigger and it runs through a CI pipeline for actual confidence that the behaviour hasn't changed.

**Comment by k-wall** [comment]
Reflecting on this, I'm with Sam.  One semver version number can rule it all.

If we wanted to version the Filter API to be truly independently, we'd treat it as an SPI (like the Servlet or JMS specification)  and give its own version number independent of the rest of Kroxylicious .   You are essentially making a strong commitment that your API is mature and will be stable over years.

I think even if we were that confident about the Filter API stability (I'm not - we are still learning about the domain), it still brings a lot of extra overhead for us.  And, as Sam points out, customers will retest their filters fully on every framework bump anyway.

I think we can have good API hygiene without needing to version separately.

**Comment by SamBarker** [comment]
Just because you mentioned the servlet spec and JMS, I don't think we can every aim for that level of API stability as our API is intrinsically tied to the Kafka Protocol and thus we support a continual evolution.

**Comment by k-wall** [comment]
> Just because you mentioned the servlet spec and JMS, I don't think we can every aim for that level of API stability as our API is intrinsically tied to the Kafka Protocol and thus we support a continual evolution.

That's a good point.

> Okay, happy to go with one version for all the modules then 👍

I'll update the release scripts etc accordingly.

**Comment by k-wall** [comment]
Following the discussion above, this issue is invalid.  Closing.
