### ISSUE TITLE
Module for annotations

### ISSUE THREAD

**Issue by tombentley** [kroxylicious/kroxylicious#731]
We currently can't use `@VisibleForTesting` in the kms modules because it lives in the runtime module. This would also be the case for other documentation annotations which we might want to use. This suggests perhaps we need a very small module (which depends on nothing itself) for such common annotations.

Furthermore, because plugins can now nest if you want to write some plugin component that is not a filter, you currently have to depend on the filter api module to get the plugin annotations. So perhaps those plugin annotations ought to also belong in this putative new module.

**Comment by showuon** [comment]
Done
