### ISSUE TITLE
Switch to direct buffers usage to perform record checksum

### ISSUE THREAD

**Issue by franz1981** [kroxylicious/kroxylicious#76]
https://issues.apache.org/jira/browse/KAFKA-13900 has been merged and we can now use direct ByteBufs (saving a copy) to have decent performance on the checksum method used under the hood.

**Comment by franz1981** [comment]
I see https://github.com/apache/kafka/commits/3.2.1 doesn't contain it, hence I suppose will land on 3,3

**Comment by k-wall** [comment]
Unfortunately, I don't see this on 3.3.1 either.

**Comment by SamBarker** [comment]
It's in the [3.4 branch](https://github.com/apache/kafka/blob/3.4/clients/src/main/java/org/apache/kafka/common/utils/Checksums.java)
