### ISSUE TITLE
Support secrets transit engine at locations other than /transit

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#779]
As described in the [HashiCorp documentation](https://developer.hashicorp.com/vault/docs/secrets/transit#setup), the transit engine can be mounted at locations other than `/transit`.

> By default, the secrets engine will mount at the name of the engine. To enable the secrets engine at a different path, use the -path argument.

```
$ vault secrets enable  --path=foo transit
Success! Enabled the transit secrets engine at: foo/
```

Currently the code assumes the default location. This might not match the user's use-case.  Configuration should allow alternative location to be specified.

**Comment by SamBarker** [comment]
We should also add to the documentation that we have a hard dependency on the vault transit engine. This ticket will make the API path configurable.
