### ISSUE TITLE
Support HTTPs vault instances and alternative sources of trust

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#780]
Currently, we are testing integration with a HashiCorp Vault instance operating over plain HTTP.  Users will want to use HTTPs to meet their security requirements.

1. We should validate that HTTPs works (it probably will) and add integration tests.
1. Some users might require an alternative source of trust, so we should allow its configuration.  The integration tests might need the same.
1. We should investigate if HashCorp Vault or HCP Vault supports mTLS.   If so, we might chose to defer the feature.

**Comment by SamBarker** [comment]
We should move mTls testing/support to a future issue. However we should validate the krxoylicious against a "real" vault instance for validation purposes.
