### ISSUE TITLE
Securely handle the HashiCorp Vault Token in Kroxylicious configuration

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#782]
When connecting to HashiCorp Vault, the client must pass a Vault Token (a secret) in order to authenticate.  Currently the token is obtained from the Kroxylicious configuration where it is stored in-line as a string.  This approach would raise red flags during a security audit.   We need a secure mechanism(s) to inject the secret.

In a Kubernetes environment, utilising a Kubernetes Secret to is an obvious choice.

**Comment by SamBarker** [comment]
We should keep in mind that we will need to handle tokens securely on bare metal deployments as well, so this could just solved at the documentation / example config level.
