### ISSUE TITLE
Write System Tests for Envelope Encryption using the HashiCorp Vault provider.

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#785]
We need system tests, initially under Kubernetes, that verify that Envelope Encryption using the HashiCorp Vault provider is functional.

**Comment by SamBarker** [comment]
I agree to the need for one, but is it really independent from the delivery of the vault provider (or envelope encryption itself) for that matter?

**Comment by k-wall** [comment]
I'm of the opinion that if we have #791, then. I'm happy to let this issue slip to 0.5.0.
