### ISSUE TITLE
Understand the performance of Record Encryption 

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#786]
We need to understand the performance impact to the user of using Envelope Encryption.
We should pick a couple of use-cases and compare performance with/without encryption/with proxy.

**Comment by SamBarker** [comment]
Pre canned workload `X` messages of `Y` size run through.
Looking for latency on produce and consume sides.

1. Kafka on its own (unecrypted)
1. Kafka & Kroxylicious (unecrypted)
1. Kafka & Kroxylicious + envelope encryption filter.
