### ISSUE TITLE
Reduce instanceof/checkcast usage vs interfaces to prevent scalability issues

### ISSUE THREAD

**Issue by franz1981** [kroxylicious/kroxylicious#79]
https://github.com/netty/netty/issues/12708 and https://github.com/netty/netty/pull/12806 better explain the issue on Netty and how to fix it.
TLDR concrete types casted/instanceof vs multiple different interfaces (they implements) cause https://bugs.openjdk.org/browse/JDK-8180450 and prevent scalability even in I/O bound cases, with many cores and NUMA nodes involved.

If the concrete type hierarchy is known, using visitor pattern or other virtual dispatch mechanisms prevent the issue to happen while keeping code safe to be implemented by users ie not affecting interface flexibility from a library perspective.

**Comment by SamBarker** [comment]
Oh good spot @k-wall no this is fixed
