### ISSUE TITLE
Release process should automate the 'release' stage of the release process down to a single manual step

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#819]
**Is your feature request related to a problem? Please describe.**

We currently have a `stage` workflow step which involves running a workflow action followed by a `release`.

1. The `stage` step branch/tags the code and stages the release artefacts.  
2. The `release` step releases the maven artefacts and merges a release PR.  This involves to developer interactions - one to kick off the workflow, one to merge the PR.   Merging the PR needs to be done in the ["right" way](https://github.com/kroxylicious/kroxylicious/blob/main/RELEASING.md#making-the-release-public) too.

It'd be nice if 2. could be reduced to a single manual interaction.

**Describe the solution you'd like**

How about if the step 2 was invoked by adding a comment to the PR. Something like:

```
/releaser release
```

or 
```
/releaser drop
```

That'd trigger the release workflow with the right argument. In addition would merge (or close) the release PR.

In addition, the stage workflow step could comment on the PR telling the developer what they need to add to the POM to test the stage artefacts.  I mean add a comment that look like this:

_Hey, that's your release successfully staged to Nexus.  It is not public available on Maven Central yet.  If you'd like to test the staged artefacts from a Maven project, you can do that by adding a `<repository>` section to your pom like the below and updating your  `io.kroxylicious:kroxylicious-bom` dependency to version `0.10.0`._

```

   <repositories>
        <repository>
            <releases>
                <enabled>true</enabled>
                <updatePolicy>always</updatePolicy>
                <checksumPolicy>warn</checksumPolicy>
            </releases>
            <name>Nexus Stage</name>
            <id>snapshots-repo</id>
            <url>https://s01.oss.sonatype.org/content/repositories/iokroxylicious-1047</url>
            <layout>default</layout>
        </repository>
    </repositories>

```

_Once you've done testing come back here and add `/releaser release` to release the artefacts, or `/release drop` to if need to abandon it._

**Describe alternatives you've considered**

**Additional context**

**Comment by SamBarker** [comment]
I like the idea.

I feel like we should ultimately automate the validation of the staging repository. I.e. the workflow checks builds the sample-filter module (repo?) using the updated repository and if that works it marks the release as shippable.

My other thought is I wonder about `/releaser` as a name. I wonder if it should be a more generic bot something like `@kroxylicious-robot publish` or `@kroxylicious-robot drop` . Though I'm not sure what else would be included

**Comment by k-wall** [comment]
We touched on this issue at triage today. We reconfirmed a desire to get this done.  @k-wall said he'd take a look.
