### ISSUE TITLE
Adopt DCO https://developercertificate.org/ across all Kroxylicious repos.

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#852]
Kroxylicious does not currently have a contributor agreement.   I think we should adopt DCO to all Kroxylicious repositories.

We should use tools such as https://probot.github.io/apps/dco/ to automate the checks that ensure incoming PRs have the appropriate sign-off.

We should also enable the options in GitHub that mean PRs raised via the GitHub UI have the appropiate metadata too. https://github.blog/changelog/2022-06-08-admins-can-require-sign-off-on-web-based-commits/

The release automation will need to change to add the --signoff flag too.

**Comment by k-wall** [comment]
We agreed that we would adopt DCO, and take the explicit path requiring --signoff.

**Comment by k-wall** [comment]
https://github.com/kroxylicious/kroxylicious/blob/865b542c5ba0f0dcd96519653713f83837bf800b/scripts/[stage-release.sh](stage-release.sh)#L154 is already using `--signoff`.

**Comment by franvila** [comment]
Thanks a lot for that investigation!

In case the workaround for the gh-pages doesn't work, we can skip installing DCO on that repo of the project. I think it can be done per repo.

**Comment by k-wall** [comment]
gh-pages is on the kroxylicious repo.

**Comment by franvila** [comment]
> gh-pages is on the kroxylicious repo. That's the repo we actually expect contributions.

You are right, I went to the `kroxylicious.github.io` repo.

**Comment by k-wall** [comment]
@franvila error on my part, commit made by asciidoctor-ghpages isn't subjected to the DCO check at all.  It pushes straight to its branch.  The DCO check is applied to the PR workflow.
