### ISSUE TITLE
[Test framework] Allow tests to be run against different versions of kafka broker

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#86]
It will be important to demonstrate that kroxy works against many versions of the kafka.  The test framework needs to allow this for both developer and CI use-cases.

* For CI use-cases, we will probably require a test matrix that executes the test suite repeatedly, varying the the kafka version.
* For developer use-cases, the developer needs the ability to set, say an environment variable that controls the kafka version.

Varying the kafka dependency at the maven level won't be the answer.  Kroxy itself uses Kafka APIs itself, and these APIs will evolve over time.  Regressing the kafka version would break kroxy code.  This implies that the brokers need to be running outside the JVM (i.e. in the containers).

It is possible that some tests will only be applicable to certain kafka versions.  There should be a way annotating a test so that it runs only if the kafka broker matches a version expectation.

**Comment by k-wall** [comment]
The test framework currently relies https://github.com/ozangunalp/kafka-native to provide an image containing the kafka native binary.  Currently location of the image is  quay.io/k_wall/kafka-native:1.0.0-SNAPSHOT, but this is temporary.

We need a mechanism to produce many different kafka-native images (one per kafka version). Perhaps the naming scheme could be:

```
 quay.io/kroxylicious/kafka-native-3.3.1:latest
 quay.io/kroxylicious/kafka-native-3.2.0:latest
```
etc.

It is possible that the substitutions may need to vary for different version.

One idea:

* Have a fork of https://github.com/ozangunalp/kafka-native within kroxylicious
* Have a branch per kafka version
* Have a Jenkins pipeline that automatically builds the kafka native image and pushes to  quay.io/kroxylicious/.

**Comment by k-wall** [comment]
@franvila are we ready to close this issue?

**Comment by franvila** [comment]
Not really, we have still pending to close the issue on Ozan repository that is a consequence of this one.
