### ISSUE TITLE
Release process generates incorrect snapshot version for main when releasing for a previous version from main.

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#869]
**Describe the bug**

main is at `0.5.0-SNAPSHOT`.
we wish to cut a `0.4.1` release from main.

Running the stage-release process generates the commit for the `0.4.1` release correctly, but the generated commit to reopen main incorrectly bumps main to 0.5.1-SNAPSHOT.

`stage-release.sh` uses `nextSnapshotIndexToIncrement`  with a value 2.  `nextSnapshotIndexToIncrement` is one based, so that's a simply instruction to increment `y` of `x.y.z`.  So `0.4.1` becomes `0.5.1` with the SNAPSHOT suffix appended owing to `nextSnapshot=true`.   `nextSnapshotIndexToIncrement` doesn't have the intelligence needed to support this use-case.

To support this use-case, I think we'd need to compute `newVersion` manually and stop relying on `nextSnapshotIndexToIncrement`.

Alternatively, we could just say if we want to release a micro release, we need to create a release branch, `release-0.4.x` in this case, and release from it.   We'd need some logic in stage-release to set nextSnapshotIndexToIncrement to 3 to support this mode of operation.

**To Reproduce**
1. Configure kroxylicious like this ...
2. Run command '....'
3. See error

**Expected behavior**

**YAML files and logs**

Attach or copy paste your kroxylicious configuration YAML (with sensitive details
like broker address redacted).
Attach or copy and paste relevant logs.

**Additional context**

**Comment by k-wall** [comment]
@SamBarker @robobario what do you think?  Using a release branch is the way I've gone in the past, as that supports the cherry-picking defects fixes to an older release.

**Comment by SamBarker** [comment]
My preference is main is releasable at all times and the version is effectively driven by the public api changes. 

I don't mind release branches but I think they should be the exception rather than the rule, we create them when we need to backport or separate out a fix. 

Either way releases should be a cheap thing for us to do.

I'm inclined to say specifying the next dev version is the cheapest option for now

**Comment by k-wall** [comment]
> I'm inclined to say specifying the next dev version is the cheapest option for now

**Comment by SamBarker** [comment]
> > I'm inclined to say specifying the next dev version is the cheapest option for now
> 
> 
> 
> that works for me - probably fixed by #869.

Yeah, I left this open incase we wanted to poke some other option.

It does look like the maven release plugin could do what we want, maybe with some custom code. Definitely **not** something I want to look in the 0.5.0 timeframe

**Comment by k-wall** [comment]
Solution we've already committed to main is good enough.  Closing issue.
