### ISSUE TITLE
[System Tests] Add HashiCorp Vault deployment to System Test framework

### ISSUE THREAD

**Issue by franvila** [kroxylicious/kroxylicious#880]
**Is your feature request related to a problem? Please describe.**
To run system tests for Topic Encryption, we would need first to be able to add HashiCorp Vault deployment to the framework. With that we should be able to manage all the keys needed for the encryption.

**Describe the solution you'd like**
It is needed to enable Transit Engine in HashiCorp Vault and we might need to test particular version(s) of HashiCorp

**Describe alternatives you've considered**
We might want to test on OpenBao (#842)

**Comment by k-wall** [comment]
Thanks @franvila that's an accurate description.  For 0.5.0, I think testing with the latest version of HashiCorp should suffice.  
Note that we've already got integration tests running HashiCorp, so that should help show the way for doing the same thing within Kubernetes.
