### ISSUE TITLE
[Tests] Merge pipelines are run randomly when a merge on main is done

### ISSUE THREAD

**Issue by franvila** [kroxylicious/kroxylicious#889]
**Describe the bug**
When a merge is done to main branch, it is supposed to be launched both Jenkins jobs, [performance](https://master-jenkins-csb-amq-streams.apps.ocp-c1.prod.psi.redhat.com/job/kroxylicious/job/kroxylicious-performance-tests-merge/) and [system tests](https://master-jenkins-csb-amq-streams.apps.ocp-c1.prod.psi.redhat.com/job/kroxylicious/job/kroxylicious-system-tests-merge/), but they are randomly selected to be launched and never both at the same time.

This occurs as well when typing a comment in a PR to launch one of them `@strimzi-ci run system tests`, sometimes we need to type it twice for the same reason.

**Expected behavior**
Both jenkins pipelines should be launched when a merge is done to main branch.

**Comment by k-wall** [comment]
let me make sure I understand the problem.  You are saying sometimes a launch that should occur does not?

**Comment by franvila** [comment]
> let me make sure I understand the problem. You are saying sometimes a launch that should occur does not?

That's right. The expected behavior when a merge to main is done is the following:
* Performance tests are launched
* System tests are launched

Currently, always one of them are launched, but never both at the same time.

**Comment by franvila** [comment]
This MR will fix the issue: https://gitlab.cee.redhat.com/strimzi/strimzi-ci/-/merge_requests/990.

Thanks @robobario for finding the issue!

**Comment by k-wall** [comment]
I noticed [#990](https://gitlab.cee.redhat.com/strimzi/strimzi-ci/-/merge_requests/990) got merged. Is this closeable?

**Comment by franvila** [comment]
Sorry, I forgot to close it yesterday.
