### ISSUE TITLE
Stronger encapsulation of keys

### ISSUE THREAD

**Issue by tombentley** [kroxylicious/kroxylicious#893]
This is an idea for the encryption filter for how we could encapsulate keys more strongly than we currently do, and in doing so provide strong guarantees on how they're used.

The motivating observation is that currently the `Kms` provides callers with direct access to `SecretKey`. So any code which has a reference to `Kms` or `DekPair` can do whatever it wants with the `SecretKey`. I think we should use Java encapsulation to provide stronger guarantees on key access. This would be helpful to someone auditing the code, for example. 

1. We keep our existing `Kms` API intact, but encapsulate it in a new `KmsMediator` class. This provides a similar APIs but without directly exposing `DekPair`. 
    ```java
    class KmsMediator {
        KmsMediator(KmsService kmsService, int maxEncryptionsPerEdek) { ... }
        CompletionStage<DataEncryptionKey<E>> generate(K keyRef) {...}
        CompletionStage<DataEncryptionKey<E>> decryptEdek(E edek) { ... }
        Serde<E> edekSerde() { ... }
        CompletionStage<K> resolveAlias(@NonNull String alias) { ... }
    }
    ```
2. `KmsMediator` takes a `KmsService` in its constructor, and strictly encapsulates the `Kms` instance it gets from it.
3. Instead of the `DekPair`- and `SecretKey`-based APIs of `Kms`, `KmsMediator` only permits access to instances of a new class `DataEncryptionKey`: 
    ```java
    class DataEncryptionKey<E> implements Destroyable {
        private final E edek; // init in ctor
        private final SecretKey key; // init in ctor
        private final AtomicInt remainingEncryptions;
        DataEncryptionKey(E edek, SecretKey, int maxEncryptions) { ... }
        Encryptor encryptor(int numEncryptions) throws ExhaustedException { ... }
        Decryptor decryptor() { ... }
        // implement Destroyable etc
    }
    ```
4. `Encryptor` would be, in effect, the encryption half of the existing `AesEncryptor`. A client could use it only to perform encryptions.
6. `Decryptor` would be the decryption half of `AesEncryptor`. A client could use it only to perform decryptions.
7. They both have access to the `SecretKey`, but ownership (the responsibility to destroy the `key`) remains with `DataEncryptionKey`.
8. Someone with a `DataEncryptionKey` can use it to perform at most `maxEncryptions` (via however many calls to encryptor as they like, so long as the total number of requested encryptions is less than the maximum). When that limit it reached the `DataEncryptionKey` can still be used to perform decryptions, until it's destroyed.
9. The `DataEncryptionKey` returned by `KmsMediator#decryptEdek()` would have no remaining encryptions. Those returned from `generate()` have `maxEncryptionsPerEdek`. 
11. All the existing code which uses `Kms` would need to be changed to use `KmsMediator`.

Notes:
* The reason I favour `KmsMediator` as separate from `Kms` is it keeps the encapsulation in the core, rather than it being a property which each KMS has to enforce by itself. This means that someone auditing the code has only to look at the Kms implementation and these 4 new classes.
* The split of the existing `AesEncryptor` would also work with the direction we're currently headed in #882, where we will end up with separate `RecordEncryptor` and `RecordDecryptor` implementations of `RecordTransformation`.

**Comment by robobario** [comment]
I wonder about destruction. If the responsibility for destruction of the `SecretKey` belongs to `DataEncryptionKey` will it have to co-ordinate with the encryptors/decryptors to ensure they have finished doing work? For example reference counting the cryptors it hands out and waiting for them to all be released before destruction of the key.

Also, if a single DataEncryptionKey is usable for both operations when would we destroy? After some configurable time idling with zero usages of encrypt or decrypt?

**Comment by tombentley** [comment]
`SecretKey` destruction is a bit underdocumented in the javax.crypto API. In particular
* the keys we currently use (`javax.crypto.spec.SecretKeySpec`) throw `DestroyFailedException`, so we can't actually destroy anything anyway (with the default `Provider`s at least).
* it's not described in the API how a user of a key (e.g. a `Cipher`) should behave if it attempts to use a key that's been destroyed. With a `SecretKeySpec` the cipher has probably copied the key bytes and forgotten about `SecretKey entirely.

So if we care about "destruction" (or at least ceasing to use a key with guarantees) we will need to manage it ourselves.

The requirements include needing to be thread-safe, but I don't think we require strict synchronicity. I.e. I think it would be fine if there are still encryptions/decryptions in-flight after the `DataEncryptionKey#destroy()` method has returned, so long as no more can start. So a single volatile boolean which the cryptor checks prior to each operation would be enough. If we could say that cryptor operations happen on a single thread then their individual accounting needn't be threadsafe. So something like this might suffice:

```java
class DataEncryptionKey<E> implements Destroyable {
    private final E edek; // init in ctor
    private final SecretKey key; // init in ctor
    private final AtomicInt remainingEncryptions;
    private volatile destroyed = false;
    DataEncryptionKey(E edek, SecretKey, int maxEncryptions) { 
        this.edek = edek;
        this.key = key;
        this.remainingEncryptions = new AtomicInteger(maxEncryptions);
    }
    public Encryptor encryptor(int numEncryptions) throws ExhaustedException {
        if (remainingEncryptions.decrementAndGet(numEncryptions) >= 0) {
            return new Encryptor(numEncryptions);
        }
        throw new ExhaustedDekException();
    }
    public Decryptor decryptor() {
        return new Decryptor();
    }
    public void destroy() {
        this.destroyed = true;
        this.key.destroy();
    }
    private class Encryptor {
        private final int remainingEncryptions;
        private final Cipher cipher;
        private Encryptor(int numEncryptions) {
            this.remainingEncryptions = numEncryptions;
        }
        public void encrypt(ByteBuffer input, ByteBuffer output) {
            if (destroyed) { throw new DestroyedDekException(); }
            if (--remainingEncryptions < 0) { throw new ExhaustedEncryptorException(); }
            // else use the key and cipher
    }
}
```

**Comment by robobario** [comment]
In your above example when/where would you expect to call `DataEncryptionKey.destroy()`? It's challenging because you could have something like:

```
DataEncryptionKey key = getKey()
Encryptor encryptor = key.encryptor(3)
encryptor.encrypt(buf1, buf2);
encryptor.encrypt(buf3, buf4);
key.destroy();
encryptor.encrypt(buf5, buf6); // throws DestroyedDekException despite the encryptor being allowed 3 encrypt invokes
```

**Comment by tombentley** [comment]
> > I think it would be fine if there are still encryptions/decryptions in-flight after the DataEncryptionKey#destroy() method has returned, so long as no more can start.
> 
> I was worried that we needed to keep the SecretKey non-destroyed while the Cipher is in use since it's initialised with `this.cipher.init(encryptMode, key, spec);`. The AES Cipher looks like it doesn't hold a reference or need to use the SecretKey beyond the init call, so I think you're right.

Yeah, that is an issue. The API doesn't define the behaviour, so what you say is true for the default security provider, but can't be guaranteed to work with all possible providers. But there's also a trade-off with build something that doesn't make such assumptions: We'd get into atomic CAS reference counting, which could harm performance even more than the `volatile closed` we have in the above. TBH these details could be changed later on easily enough without breaking the key encapsulation, so for now "worse is better" imho.

**Comment by tombentley** [comment]
> In your above example when/where would you expect to call `DataEncryptionKey.destroy()`? 

I think I see a `DataEncryptionKey` as being a thing which can safely be cached, and shared between the encrypt path cache and the decrypt path cache. An instance would be evicted from the encrypt path cache when exhausted or after a timeout, and evicted from the decrypt path cache after a timeout (decrypt operations aren't limited to a count). I think the sharing could be useful because we'd expect consumers to often be fetching at the end of the log while producers are appending, so we'd often need the same key on both encryption and decryption paths. 

Which makes me realise that semantics we need are not exactly those of `Destroyable`. We probably need a reference count (or two flags) and perhaps two methods (`dropForEncrypt()` and `dropForDecrypt()`) which decrement the ref count. An instance obtained via `generateDek()` would have an initial reference count of 2 and could live in both caches. An instance obtained via `unwrap` would have an initial reference count of 1 and `remainingEncryptions=0` (so it couldn't be used on the encryption path anyway). When the reference count hits 0 we call `key.destroy()`. If we couldn't guarantee that `dropForEncrypt()`/`dropForDecrypt()` is only called once on eviction from the cache then we might need two flags to avoid things getting messed up. 

> It's challenging because you could have something like:
> 
> ```
> DataEncryptionKey key = getKey()
> Encryptor encryptor = key.encryptor(3)
> encryptor.encrypt(buf1, buf2);
> encryptor.encrypt(buf3, buf4);
> key.destroy();
> encryptor.encrypt(buf5, buf6); // throws DestroyedDekException despite the encryptor being allowed 3 encrypt invokes
> ```

True. That's not the end of the world. We could handle that exception at the top level and just try again with a freshly minted DEK, similar to how we'll have to handle an `ExhaustedDekException`.

Alternatively we change the guarantee slightly and allow a cryptor, once created, to use the key, but require the caller to release the cryptor once they're done with it. Reference count in the `DataEncryptionKey`. Ensure that we obtain fresh cryptors from the `DataEncryptionKey` for each request/response. This might be preferable as it means each encrypt/decrypt doesn't need to check the `volatile destroyed`.
