### ISSUE TITLE
Error in TLS configuration

### ISSUE THREAD

**Issue by saschavg** [kroxylicious/kroxylicious#896]
**Problem**
The section about the TLS configurations state that "passwordFile" key can be used to point to the password file.
- This should be "filePath"

**Documentation Link**
[Downstream TLS](https://kroxylicious.io/kroxylicious/#_downstream_tls)
[Upstream TLS](https://kroxylicious.io/kroxylicious/#_upstream_tls)

**Comment by k-wall** [comment]
@saschavg yes, you are correct.  The documentation is in error. I'll raise a PR now to fix that.

**Comment by k-wall** [comment]
Actually, I prefer `passwordFile` expressed by the documentation. I think it self documents better.

```yaml
          storePassword:
            passwordFile: /opt/cert/store.password      # <2>
```

I'm going to change the implementation, and use a @JsonAlias to support filePath too.
