### ISSUE TITLE
Enable Filters to determine whether code is executing in the filter dispatch thread

### ISSUE THREAD

**Issue by robobario** [kroxylicious/kroxylicious#904]
While implementing #895 we found that it could be useful if Filter's had a mechanism to determine if code is executing in the filter dispatch thread. Filters could use this to decide whether they need to switch back to the dispatch thread to update some Filter state.

Currently we have javadoc describing our guarantee that construction and dispatch of Filter methods is associated with one thread. And the `FilterFactoryContext` exposes `ScheduledExecutorService eventLoop();` so if we keep the same naming we could add a method like `boolean inEventLoop()` to FilterFactoryContext. I think we should consider adding these two methods to `FilterContext` as well.

Though perhaps we should move away from the netty naming and come up with a name like `filterDispatchThread`.

**Comment by showuon** [comment]
Maybe changing the name could come first in 0.5.0.
