### ISSUE TITLE
SNYK-CODE CWE-547 Hardcoded secret in AesGcmEncryptor and InMemoryKms (false positives?)

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#936]
**Describe the bug**

A snyk scan is reporting two SNYK-CODE CWE-547 for Kroxylicious topic encryption related code.  Both appear to be false positives.  You can reason about the fact that the buffer is always securely  initialised before any encrypt operation.

```
Hardcoded value array {...} is used as a cipher initialization value. Generate the value with a cryptographically strong random number generator such as java.security.SecureRandom instead.
```

[AesGcmEncryptor.java](https://github.com/kroxylicious/kroxylicious/blob/360cf78c01e117a52509ca4e70d90675dec6be99/kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/inband/AesGcmEncryptor.java#L41)
```java
this.iv = newbyte[ivSizeBytes]; // Line 41:23 SOURCE
var spec = newGCMParameterSpec(numAuthBits, iv); // Line 114:24 SINK
```

In this case, presumable the scanner is not able to determine that `#outputSize` which initialises the buffer is always called before `#encrypt` despite the lastCall state guard.

[InMemoryKms.java](https://github.com/kroxylicious/kroxylicious/blob/360cf78c01e117a52509ca4e70d90675dec6be99/kroxylicious-kms-provider-kroxylicious-inmemory/src/main/java/io/kroxylicious/kms/provider/kroxylicious/inmemory/InMemoryKms.java#L132)
```
byte[] iv = new byte[numIvBytes];  // Line 133:25 SOURCE
var spec = new GCMParameterSpec(numAuthBits, iv); // Line 135:24 SINK
```

In this second case, it is particularly bizarre as the buffer is initialised in same method method, in line.   (Might be worthy of a snyk issue??).

**Expected behavior**

A clean Snyk report.

**Additional context**
Either we should reexpress the code to avoid the false positives (if reasonable). The fallback is to add a ignore.
https://docs.snyk.io/scan-using-snyk/policies/the-.snyk-file

**Comment by robobario** [comment]
From experimentation it's a false positive. If the iv is declared (and doesn't get routed through other objects) and then used in the GCMParameterSpec constructor  in the same source file you get a failure.

I created a [reproducer here](https://github.com/robobario/snyk-false-positive) and made a snyk ticket.

Meanwhile, do we need to worry about these false positives in terms of public impact? I don't believe this contributes to the snyk report for our opensource artefacts. You can make a maven project depending on `io.kroxylicious:kroxylicious-kms-provider-kroxylicious-inmemory:0.4.0` (contains the flagged code) and snyk scan it, no failures reported. I guess a researcher would have to create a CVE.

And just for interest you can workaround the static analysis in several ways (likely more):

1. static method to do the random byte generation in another source file (I'm thinking the analysis is per-file) like `static byte[] randomBytes(SecureRandom random, int numBytes)` :check:
2. avoid the GCMParameterSpec constructor call with functions: :check:
``` java
byte[] iv = new byte[numIvBytes];
secureRandom.nextBytes(iv);
BiFunction<Integer, byte[], GCMParameterSpec> gcmFunc = GCMParameterSpec::new;
var spec = gcmFunc.apply(numAuthBits, iv);
```
3. route it through a record :check:
``` java
record GcmParams(byte[] iv){}
...
byte[] iv = new byte[numIvBytes];
secureRandom.nextBytes(iv);
GcmParams gcmParams = new GcmParams(iv);
var spec = new GCMParameterSpec(numAuthBits, gcmParams.iv());
```

**Comment by robobario** [comment]
I'm in favour of ignoring them with snyk config since the check seems broken, rather than shuffling code around to satisfy the broken thing.

**Comment by k-wall** [comment]
@robobario thorough work, thank you.

> I created a [reproducer here](https://github.com/robobario/snyk-false-positive) and made a snyk ticket.

Could you link the ticket?

> I'm in favour of ignoring them with snyk config since the check seems broken

Agreed.

**Comment by robobario** [comment]
On further investigation it appears you can only choose to completely exclude a file from code scanning

https://docs.snyk.io/scan-with-snyk/snyk-code/import-repository-to-snyk/excluding-directories-and-files-from-the-import-process

I think the per-vulnerability ignores you can do are only relevant to dependency chain scanning (like `snyk test`)

**Comment by k-wall** [comment]
Can't we add file/rule specific rule like this?

```shell
snyk ignore --id='CWE-547' --expiry='2025-01-01' --reason='false positive'  --path=./kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/inband/AesGcmEncryptor.java
```

that generates a `.snyk` file (untested)

```
# Snyk (https://snyk.io) policy file, patches or ignores known vulnerabilities.
version: v1.25.0
# ignores vulnerabilities until expiry date; change duration by modifying expiry date
ignore:
  CWE-547:
    - ./kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/inband/AesGcmEncryptor.java:
        reason: false positive
        expires: 2025-01-01T00:00:00.000Z
        created: 2024-02-13T10:03:45.651Z
```

**Comment by robobario** [comment]
Didn't get to this today, I'll give it a go tomorrow uploading a sample project. (also for me that `snyk ignore` command looks like it was talking to the API and I got "Only administrators can ignore issues. Please contact an administrator to ignore this issue.")

**Comment by k-wall** [comment]
> "Only administrators can ignore issues. Please contact an administrator to ignore this issue.")

curious, my snyk ignore command just seems to write to the local file. I hadn't done a `snyk auth` or anything.

**Comment by k-wall** [comment]
@robobario yes, you are right.  I'd didn't appreciate that the different sort of scans had different ignore mechanisms.

https://docs.snyk.io/snyk-cli/scan-and-maintain-projects-using-the-cli/snyk-cli-for-snyk-code/exclude-directories-and-files-from-snyk-code-cli-tests says

> Consider excluding directories and files only if you do not publish or compile them into production. If a trace goes through an excluded file or directory with existing vulnerabilities, Snyk might miss potential issues.

on that basis, an exclusion for InMemoryKms.java seems reasonable as this is non-production code.   Excluding CipherSpec.java on the other hand could be harmful, as it would mean that scanner could miss real vulnerabilities in addition to CWE-547 false positive.

**Comment by SamBarker** [comment]
> I'd didn't appreciate that the different sort of scans had different ignore mechanisms.

If only one type of scan was useful it would be an improvement...
