### ISSUE TITLE
Shell check is very unimpressed

### ISSUE THREAD

**Issue by SamBarker** [kroxylicious/kroxylicious#941]
**Describe the bug**
Shellcheck scanning of kroxylicious finds a multitude of warnings, mostly around posix compliance and quoting to prevent word splitting. However it does also flag

```
SHELLCHECK_WARNING ([CWE-829](https://cwe.mitre.org/data/definitions/829.html)): [[#def108]](https://cov01.lab.eng.brq2.redhat.com/osh/task/448033/log/kroxylicious-0.5.0.redhat-00016/scan-results-all.html#def108) [important]
kroxylicious-app/src/assembly/run-java.sh:474:8: warning[[SC2091](https://github.com/koalaman/shellcheck/wiki/SC2091)]: Remove surrounding $() to avoid executing output (or use eval if intentional).
#  472|     if [ -n "${JAVA_APP_NAME:-}" ]; then
#  473|       # Not all shells support the 'exec -a newname' syntax..
#  474|->     if $(exec -a test true 2>/dev/null); then
#  475|         echo "-a '${JAVA_APP_NAME}'"
```

**To Reproduce**
Run shellcheck on the scripts.

**Expected behavior**
Ideally a clean run, but certainly no important failures.

**YAML files and logs**

Attach or copy paste your kroxylicious configuration YAML (with sensitive details
like broker address redacted).
Attach or copy and paste relevant logs.

**Additional context**

**Comment by k-wall** [comment]
+1 to pushing this check left

**Comment by SamBarker** [comment]
https://github.com/marketplace/actions/shellcheck <-- would allow us to automate checks

**Comment by SamBarker** [comment]
Resolved with https://github.com/kroxylicious/kroxylicious/pull/996
