### ISSUE TITLE
System test pipeline runs push to surprising container registry location

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#963]
>  (from https://github.com/kroxylicious/kroxylicious/issues/961#issuecomment-1932007196) Currently, the system test pipeline compiles and pushes a new image to quay with the code generated from the PR. The thing here is that we are overwriting the image located at quay.io/kroxylicious/kroxylicious:0.5.0-SNAPSHOT every time.

 Oh..  that violates least surprise.   You wouldn't expect a public image `0.5.0-SNAPSHOT` to contain a PR build.

If we want the PR images on the public repo (maybe that helps some use-cases), then they should be tagged with the (short) commit sha (`git rev-list --max-count=1 --abbrev-commit HEAD`), so we understand which PR they related to and we have uniqueness.

We should set the [tag-expiration label](https://access.redhat.com/documentation/ja-jp/red_hat_quay/3.3/html/use_red_hat_quay/tag-expiration) on the image so they clean up automatically (~6h)?

You can pass additional label from the `docker build --label "name=value` so it should be easy to adapt the [script](https://gitlab.cee.redhat.com/strimzi/strimzi-ci/-/blob/master/vars/kroxy.groovy?ref_type=heads#L127).

_Originally posted by @k-wall in https://github.com/kroxylicious/kroxylicious/issues/961#issuecomment-1932007196_

**Comment by franvila** [comment]
MR done https://gitlab.cee.redhat.com/strimzi/strimzi-ci/-/merge_requests/1007

**Comment by k-wall** [comment]
Thank you!
