### ISSUE TITLE
API should permit the modification of the clientid

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#98]
For the multi-tenant user case, we will want to apply a tenant prefix to the `clientid` so that clientid of different tenants don't conflict.  The `ClientId` is part of the [RequestHeader](https://github.com/apache/kafka/blob/trunk/clients/src/main/resources/common/message/RequestHeader.json#L39), but current the kroxy API doesn't (easily) permit that part of the request to be mutated.

The API needs to be able to support these types of transformations.

**Comment by k-wall** [comment]
@tombentley and I discussed in another channel.

> Re "Does kroxy API actually permit the header to be changed?":

@tombentley  said:
currently yes, but you'd have to subclass KrpcFilter directly to do so.
With my proposed change to avoid the checkcast pref problem we'd need to change the API to also pass the header I guess, and allow passing that back through the methods of FilterContext. Eugh!
An alternative might be to expose the same information via the context.

**Comment by k-wall** [comment]
Thinking about expose the same information on the filter context, my first idea was to add the following method to `KrpcFilterContext`.

```
org.apache.kafka.common.messag.RequestHeaderData requestHeaders();
```

the user of the API could then use that inspect the current request headers, or mutate them via them via the `#set` methods. I don't believe there is a use-case for inspecting/mutating the response headers, so I don't think there is a need for  `#responseHeaders()`

There's a couple of things I don't like:

# what would `requestHeaders()` do if you were handling the response?  `IllegalStateException` i suppose?
# it seems weird to give the caller the ability to `#setRequestApiKey`. The API key is not mutatble.
# if we have #setRequestApiVersion do we need argument 1 of  #sendRequest(apiVersion) anymore?

**Comment by SamBarker** [comment]
I guess part of it comes down to something that keeps rumbling around the back of my head. Do we want expose Kafka API's directly or should we have wrapper types? 

If we expose the Kafka API's directly we have to live with strangeness like `RequestHeaderData#setRequestApiKey` being exposed. Equally do wrapper types provide us enough value compared to the hassle of building/generating and maintaining them?
